=== microsoft/azure-pipelines-tasks/task-lib/tasks.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "id": "https://raw.githubusercontent.com/Microsoft/azure-pipelines-task-lib/master/tasks.schema.json",
  "title": "Azure DevOps Tasks schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string",
      "description": "A unique guid for this task",
      "pattern": "^[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}$"
    },
    "name": {
      "type": "string",
      "description": "Name with no spaces",
      "pattern": "^[A-Za-z0-9\\-]+$"
    },
    "friendlyName": {
      "type": "string",
      "description": "Descriptive name (spaces allowed). Must be <= 40 chars"
    },
    "description": {
      "type": "string",
      "description": "Detailed description of what your task does"
    },
    "helpUrl": {
      "type": "string"
    },
    "helpMarkDown": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "preview": {
      "type": "boolean"
    },
    "deprecated": {
      "type": "boolean",
      "description": "Task is deprecated only when the latest version is marked as deprecated. Deprecated tasks appear at the end of searches under a section that is collapsed by default."
    },
    "removalDate": {
      "type": "string",
      "description": "The date included in the depreciation warning after which the task may no longer be available. Format: YYYY-MM-DD",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
    },
    "deprecationMessage": {
      "type": "string",
      "description": "A tailored deprecation message containing detailed information about the task deprecation (besides the removal date and the URL leading to the task documentation) in addition to the common deprecation message."
    },
    "showEnvironmentVariables": {
      "type": "boolean",
      "description": "Toggles showing the environment variable editor in the task editor UI. Allows passing environment variables to script based tasks."
    },
    "runsOn": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Agent",
          "MachineGroup",
          "Server",
          "ServerGate",
          "DeploymentGroup"
        ]
      }
    },
    "visibility": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Build",
          "Release"
        ]
      }
    },
    "category": {
      "type": "string",
      "description": "Where the task appears in Azure DevOps. Use the 'Azure *' categories for Azure DevOps and Azure DevOps Server 2019. Use the other categories for Team Foundation Server 2018 and below.",
      "enum": [
        "Build",
        "Utility",
        "Test",
        "Package",
        "Deploy",

        "Azure Repos",
        "Azure Boards",
        "Azure Pipelines",
        "Azure Test Plans",
        "Azure Artifacts"
      ]
    },
    "groups": {
      "type": "array",
      "description": "Describes groups that task properties may be logically grouped by in the UI.",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "name",
          "displayName"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "displayName": {
            "type": "string"
          },
          "isExpanded": {
            "type": "boolean"
          },
          "visibleRule": {
            "type": "string",
            "description": "Allow's you to define a rule which dictates when the group will be visible to a user, for example \"variableName1 != \\\"\\\" && variableName2 = value || variableName3 NotEndsWith value\""
          }
        }
      }
    },
    "demands": {
      "type": "array",
      "description": "Allows you to define a list of demands that a build agent requires to run this build task.",
      "items": {
        "type": "string"
      }
    },
    "minimumAgentVersion": {
      "type": "string",
      "pattern": "^\\d+\\.\\d+(\\.\\d+)?$"
    },
    "version": {
      "type": "object",
      "additionalProperties": false,
      "description": "Always update this when you release your task, so that the agents utilize the latest code.",
      "required": [
        "Major",
        "Minor",
        "Patch"
      ],
      "properties": {
        "Major": {
          "type": "number"
        },
        "Minor": {
          "type": "number"
        },
        "Patch": {
          "type": "number"
        }
      }
    },
    "instanceNameFormat": {
      "type": "string",
      "description": "This is how the task will be displayed within the build step list - you can use variable values by using $(variablename)"
    },
    "releaseNotes": {
      "type": "string"
    },
    "inputs": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "name",
          "label",
          "type"
        ],
        "properties": {
          "name": {
            "type": "string",
            "description": "The variable name to use to store the user-supplied value",
            "pattern": "^[A-Za-z][A-Za-z0-9]*$"
          },
          "aliases": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "label": {
            "type": "string",
            "description": "The text displayed to the user for the input label"
          },
          "type": {
            "type": "string",
            "description": "The type that dictates the control rendered to the user.",
            "anyOf": [
              {
                "enum": [
                  "boolean",
                  "filePath",
                  "multiLine",
                  "pickList",
                  "radio",
                  "secureFile",
                  "string",
                  "int",
                  "identities",
                  "querycontrol"
                ]
              },
              {
                "type": "string",
                "pattern": "^connectedService\\:.+$"
              }
            ]
          },
          "defaultValue": {
            "type": [
              "string",
              "boolean"
            ],
            "description": "The default value to apply to this input."
          },
          "required": {
            "type": "boolean",
            "description": "Whether the input is a required field (default is false).",
            "default": false
          },
          "helpMarkDown": {
            "type": "string",
            "description": "Help to be displayed when hovering over the help icon for the input. To display URLs use the format [Text To Display](http://Url)"
          },
          "groupName": {
            "type": "string",
            "description": "Setting this to the name of a group defined in 'groups' will place the input into that group."
          },
          "visibleRule": {
            "type": "string",
            "description": "Allow's you to define a rule which dictates when the input will be visible to a user, for example \"variableName1 != \\\"\\\" && variableName2 = value || variableName3 NotEndsWith value\""
          },
          "properties": {
            "type": "object",
            "properties": {
              "EditableOptions": {
                "type": "string",
                "enum": [
                  "True",
                  "False"
                ]
              },
              "MultiSelect": {
                "type": "string",
                "enum": [
                  "True",
                  "False"
                ]
              },
              "MultiSelectFlatList": {
                "type": "string",
                "enum": [
                  "True",
                  "False"
                ]
              },
              "DisableManageLink": {
                "type": "string",
                "enum": [
                  "True",
                  "False"
                ]
              },
              "IsSearchable": {
                "type": "string",
                "enum": [
                  "True",
                  "False"
                ]
              },
              "PopulateDefaultValue": {
                "type": "string",
                "enum": [
                  "True",
                  "False"
                ]
              },
              "isVariableOrNonNegativeNumber": {
                "type": "string",
                "enum": [
                  "true",
                  "false"
                ]
              },
              "resizable": {
                "type": "boolean"
              },
              "rows": {
                "type": "string",
                "pattern": "^\\d+$"
              },
              "maxLength": {
                "type": "string",
                "pattern": "^\\d+$"
              },
              "editorExtension": {
                "type": "string"
              },
              "EndpointFilterRule": {
                "type": "string"
              }
            }
          },
          "options": {
            "type": "object",
            "additionalProperties": true
          }
        }
      }
    },
    "dataSourceBindings": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "target": {
            "type": "string"
          },
          "endpointId": {
            "type": "string"
          },
          "dataSourceName": {
            "type": "string"
          },
          "parameters": {
            "type": "object"
          },
          "resultTemplate": {
            "type": "string"
          },
          "endpointUrl": {
            "type": "string"
          },
          "resultSelector": {
            "type": "string"
          },
          "RequestVerb": {
            "type": "string",
            "enum": [
              "GET",
              "POST",
              "DELETE",
              "OPTIONS",
              "HEAD",
              "PUT",
              "TRACE",
              "PATCH"
            ]
          },
          "requestContent": {
            "type": "string"
          },
          "callbackContextTemplate": {
            "type": "string"
          },
          "callbackRequiredTemplate": {
            "type": "string"
          },
          "initialContextTemplate": {
            "type": "string"
          }
        }
      }
    },
    "sourceDefinitions": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "target": {
            "type": "string"
          },
          "endpoint": {
            "type": "string"
          },
          "selector": {
            "type": "string"
          },
          "keySelector": {
            "type": "string"
          },
          "authKey": {
            "type": "string"
          }
        }
      }
    },
    "prejobexecution": {
      "type": "object",
      "additionalProperties": false,
      "description": "Execution options for this task (on Pre-Job stage)",
      "properties": {
        "Node16": {
          "$ref": "#/definitions/executionObject"
        },
        "Node10": {
          "$ref": "#/definitions/executionObject"
        },
        "Node": {
          "$ref": "#/definitions/executionObject"
        },
        "PowerShell3": {
          "$ref": "#/definitions/executionObject"
        },
        "PowerShell": {
          "$ref": "#/definitions/executionObject"
        }
      }
    },
    "execution": {
      "type": "object",
      "additionalProperties": false,
      "description": "Execution options for this task",
      "properties": {
        "Node16": {
          "$ref": "#/definitions/executionObject"
        },
        "Node10": {
          "$ref": "#/definitions/executionObject"
        },
        "Node": {
          "$ref": "#/definitions/executionObject"
        },
        "PowerShell3": {
          "$ref": "#/definitions/executionObject"
        },
        "PowerShell": {
          "$ref": "#/definitions/executionObject"
        }
      }
    },
    "postjobexecution": {
      "type": "object",
      "additionalProperties": false,
      "description": "Execution options for this task (on Post-Job stage)",
      "properties": {
        "Node16": {
          "$ref": "#/definitions/executionObject"
        },
        "Node10": {
          "$ref": "#/definitions/executionObject"
        },
        "Node": {
          "$ref": "#/definitions/executionObject"
        },
        "PowerShell3": {
          "$ref": "#/definitions/executionObject"
        },
        "PowerShell": {
          "$ref": "#/definitions/executionObject"
        }
      }
    },
    "messages": {
      "type": "object"
    },
    "outputVariables": {
      "type": "array",
      "description": "Describes output variables of task.",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "type": "string",
            "description": "The variable name",
            "pattern": "^[A-Za-z][A-Za-z0-9]*$"
          },
          "description": {
            "type": "string",
            "description": "Detailed description of the variable"
          }
        }
      }
    },
    "restrictions": {
      "type": "object",
      "additionalProperties": false,
      "description": "Restrictions on tasks",
      "properties": {
        "commands": {
          "type": "object",
          "additionalProperties": false,
          "description": "Restrictions on available task commands",
          "properties": {
            "mode": {
              "type": "string",
              "enum": [
                "any",
                "restricted"
              ]
            }
          }
        },
        "settableVariables": {
          "type": "object",
          "additionalProperties": false,
          "description": "Restrictions on which variables can be set via commands",
          "properties": {
            "allowed": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "$schema": {
      "type": "string"
    }
  },
  "definitions": {
    "executionObject": {
      "type": "object",
      "additionalProperties": true,
      "required": [
          "target"
      ],
      "properties": {
        "target": {
          "type": "string",
          "description": "The target file to be executed. You can use variables here in brackets e.g. $(currentDirectory)\filename.ps1"
        },
        "platforms": {
          "type": "array",
          "items": {
            "enum": [
              "windows"
            ]
          }
        },
        "argumentFormat": {
          "type": "string"
        },
        "workingDirectory": {
          "type": "string"
        }
      }
    }
  }
}

=== microsoft/azure-pipelines-tasks/Tasks/InstallAppleCertificate/task.json
{
    "id": "d2eff759-736d-4b7b-8554-7ba0960d49d6",
    "name": "InstallAppleCertificate",
    "friendlyName": "Install Apple Certificate",
    "description": "Install an Apple certificate required to build on a macOS agent",
    "helpMarkDown": "[More Information](https://go.microsoft.com/fwlink/?LinkID=862067)",
    "category": "Utility",
    "visibility": [
        "Build",
        "Release"
    ],
    "author": "Microsoft Corporation",
    "version": {
        "Major": 1,
        "Minor": 126,
        "Patch": 1
    },
    "runsOn": [
        "Agent",
        "DeploymentGroup"
    ],
    "demands": [
        "xcode"
    ],
    "groups":[
        {
            "name": "advanced",
            "displayName": "Advanced",
            "isExpanded": true
        }
    ],
    "minimumAgentVersion": "2.116.0",
    "instanceNameFormat": "Install an Apple certificate",
    "inputs": [
        {
            "name": "certSecureFile",
            "type": "secureFile",
            "label": "Certificate (P12)",
            "defaultValue": "",
            "required": true,
            "helpMarkDown": "Select the certificate (.p12) that was uploaded to `Secure Files` to install on the macOS agent."
        },
        {
            "name": "certPwd",
            "type": "string",
            "label": "Certificate (P12) Password",
            "required": false,
            "helpMarkDown": "Password to the Apple certificate (.p12). Use a new build variable with its lock enabled on the `Variables` tab to encrypt this value."
        },
        {
            "name": "keychain",
            "type": "pickList",
            "label": "Keychain",
            "defaultValue": "temp",
            "required": true,
            "options": {
                "default": "Default Keychain",
                "temp": "Temporary Keychain",
                "custom": "Custom Keychain"
            },
            "helpMarkDown": "Select the keychain in which to install the Apple certificate. A temporary keychain will always be deleted after the build or release is complete.",
            "groupName": "advanced"
        },
        {
            "name": "keychainPassword",
            "type": "string",
            "label": "Keychain Password",
            "required": false,
            "helpMarkDown": "Password to unlock the keychain. Use a new build variable with its lock enabled on the `Variables` tab to encrypt this value. A password is generated for the temporary keychain if not specified.",
            "groupName": "advanced"
        },
        {
            "name": "customKeychainPath",
            "type": "string",
            "label": "Custom Keychain Path",
            "required": true,
            "helpMarkDown": "Full path to a custom keychain file. The keychain will be created if it does not exist.",
            "visibleRule": "keychain = custom",
            "groupName": "advanced"
        },
        {
            "name": "deleteCert",
            "type": "boolean",
            "label": "Delete Certificate from Keychain",
            "required": false,
            "helpMarkDown": "Select to delete the certificate from the keychain after the build or release is complete.",
            "visibleRule": "keychain = custom || keychain = default",
            "groupName": "advanced"
        },
        {
            "name": "deleteCustomKeychain",
            "type": "boolean",
            "label": "Delete Custom Keychain",
            "required": false,
            "helpMarkDown": "Select to delete the custom keychain from the agent after the build or release is complete.",
            "visibleRule": "keychain = custom",
            "groupName": "advanced"
        },
        {
            "name": "signingIdentity",
            "type": "string",
            "label": "Certificate Signing Identity",
            "required": false,
            "helpMarkDown": "The Common Name of the subject in the signing certificate.  Will attempt to parse the Common Name if this is left empty.",
            "groupName": "advanced"
        }
    ],
    "outputVariables": [
        {
            "name": "signingIdentity",
            "description": "The resolved Common Name of the subject in the signing certificate. Either supplied as an input or parsed from the P12 certificate file."
        },
        {
            "name": "keychainPath",
            "description": "The path for the keychain file with the certificate."
        }
    ],
    "prejobexecution": {
        "Node": {
            "target": "preinstallcert.js",
            "argumentFormat": ""
        }
    },
    "postjobexecution": {
        "Node": {
            "target": "postinstallcert.js",
            "argumentFormat": ""
        }
    },
    "messages": {
        "INVALID_P12": "Unable to find the certificate SHA1 hash and common name (CN). Verify that the certificate is a valid P12.",
        "NoP12PwdWarning": "No P12 password supplied. If the P12 file requires a password, best practice is to supply it as process variable and mark it secret (lock icon)."
    }
}

=== microsoft/azure-pipelines-tasks/Tasks/PyPIPublisher/task.loc.json
{
  "id": "2d8a1d60-8ccd-11e7-a792-11ac56e9f553",
  "name": "PyPIPublisher",
  "friendlyName": "ms-resource:loc.friendlyName",
  "description": "ms-resource:loc.description",
  "author": "Microsoft Corporation",
  "helpMarkDown": "ms-resource:loc.helpMarkDown",
  "category": "Utility",
  "visibility": [
    "Build",
    "Release"
  ],
  "demands": [],
  "version": {
    "Major": 0,
    "Minor": 1,
    "Patch": 0
  },
  "minimumAgentVersion": "2.0.0",
  "instanceNameFormat": "ms-resource:loc.instanceNameFormat",
  "inputs": [
    {
      "name": "wd",
      "type": "filePath",
      "label": "ms-resource:loc.input.label.wd",
      "required": true,
      "helpMarkDown": "ms-resource:loc.input.help.wd"
    },
    {
      "name": "serviceEndpoint",
      "type": "connectedService:generic",
      "label": "ms-resource:loc.input.label.serviceEndpoint",
      "required": true,
      "helpMarkDown": "ms-resource:loc.input.help.serviceEndpoint"
    }
  ],
  "execution": {
    "Node": {
      "target": "publisher.js",
      "argumentFormat": ""
    }
  }
}

=== microsoft/azure-pipelines-tasks/Tasks/DownloadBuildArtifact/task.loc.json
{
  "id": "a433f589-fce1-4460-9ee6-44a624aeb1fb",
  "name": "DownloadBuildArtifact",
  "friendlyName": "ms-resource:loc.friendlyName",
  "description": "ms-resource:loc.description",
  "helpMarkDown": "ms-resource:loc.helpMarkDown",
  "category": "Utility",
  "author": "Microsoft Corporation",
  "preview": true,
  "version": {
    "Major": 0,
    "Minor": 1,
    "Patch": 48
  },
  "demands": [],
  "inputs": [
    {
      "name": "buildId",
      "type": "pickList",
      "label": "ms-resource:loc.input.label.buildId",
      "required": false,
      "helpMarkDown": "ms-resource:loc.input.help.buildId",
      "defaultValue": "$(Build.BuildId)",
      "options": {
        "$(Build.BuildId)": "The current build"
      }
    },
    {
      "name": "artifactName",
      "type": "string",
      "label": "ms-resource:loc.input.label.artifactName",
      "defaultValue": "drop",
      "required": true,
      "helpMarkDown": "ms-resource:loc.input.help.artifactName"
    },
    {
      "name": "downloadPath",
      "type": "string",
      "label": "ms-resource:loc.input.label.downloadPath",
      "defaultValue": "$(System.ArtifactsDirectory)",
      "required": true,
      "helpMarkDown": "ms-resource:loc.input.help.downloadPath"
    }
  ],
  "dataSourceBindings": [],
  "instanceNameFormat": "ms-resource:loc.instanceNameFormat",
  "execution": {
    "Node": {
      "target": "main.js",
      "argumentFormat": ""
    }
  },
  "messages": {
    "FileContainerCredentialsNotFound": "ms-resource:loc.messages.FileContainerCredentialsNotFound",
    "FileContainerInvalidArtifact": "ms-resource:loc.messages.FileContainerInvalidArtifact",
    "FileContainerInvalidArtifactData": "ms-resource:loc.messages.FileContainerInvalidArtifactData",
    "ArtifactProviderNotFound": "ms-resource:loc.messages.ArtifactProviderNotFound",
    "DownloadError": "ms-resource:loc.messages.DownloadError",
    "DownloadingFile": "ms-resource:loc.messages.DownloadingFile",
    "InvalidBuildId": "ms-resource:loc.messages.InvalidBuildId"
  }
}
