=== microsoft/azure-pipelines-tasks/task-lib/tasks.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "id": "https://raw.githubusercontent.com/Microsoft/azure-pipelines-task-lib/master/tasks.schema.json",
  "title": "Azure DevOps Tasks schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string",
      "description": "A unique guid for this task",
      "pattern": "^[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}$"
    },
    "name": {
      "type": "string",
      "description": "Name with no spaces",
      "pattern": "^[A-Za-z0-9\\-]+$"
    },
    "friendlyName": {
      "type": "string",
      "description": "Descriptive name (spaces allowed). Must be <= 40 chars"
    },
    "description": {
      "type": "string",
      "description": "Detailed description of what your task does"
    },
    "helpUrl": {
      "type": "string"
    },
    "helpMarkDown": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "preview": {
      "type": "boolean"
    },
    "deprecated": {
      "type": "boolean",
      "description": "Task is deprecated only when the latest version is marked as deprecated. Deprecated tasks appear at the end of searches under a section that is collapsed by default."
    },
    "removalDate": {
      "type": "string",
      "description": "The date included in the depreciation warning after which the task may no longer be available. Format: YYYY-MM-DD",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
    },
    "deprecationMessage": {
      "type": "string",
      "description": "A tailored deprecation message containing detailed information about the task deprecation (besides the removal date and the URL leading to the task documentation) in addition to the common deprecation message."
    },
    "showEnvironmentVariables": {
      "type": "boolean",
      "description": "Toggles showing the environment variable editor in the task editor UI. Allows passing environment variables to script based tasks."
    },
    "runsOn": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Agent",
          "MachineGroup",
          "Server",
          "ServerGate",
          "DeploymentGroup"
        ]
      }
    },
    "visibility": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Build",
          "Release"
        ]
      }
    },
    "category": {
      "type": "string",
      "description": "Where the task appears in Azure DevOps. Use the 'Azure *' categories for Azure DevOps and Azure DevOps Server 2019. Use the other categories for Team Foundation Server 2018 and below.",
      "enum": [
        "Build",
        "Utility",
        "Test",
        "Package",
        "Deploy",

        "Azure Repos",
        "Azure Boards",
        "Azure Pipelines",
        "Azure Test Plans",
        "Azure Artifacts"
      ]
    },
    "groups": {
      "type": "array",
      "description": "Describes groups that task properties may be logically grouped by in the UI.",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "name",
          "displayName"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "displayName": {
            "type": "string"
          },
          "isExpanded": {
            "type": "boolean"
          },
          "visibleRule": {
            "type": "string",
            "description": "Allow's you to define a rule which dictates when the group will be visible to a user, for example \"variableName1 != \\\"\\\" && variableName2 = value || variableName3 NotEndsWith value\""
          }
        }
      }
    },
    "demands": {
      "type": "array",
      "description": "Allows you to define a list of demands that a build agent requires to run this build task.",
      "items": {
        "type": "string"
      }
    },
    "minimumAgentVersion": {
      "type": "string",
      "pattern": "^\\d+\\.\\d+(\\.\\d+)?$"
    },
    "version": {
      "type": "object",
      "additionalProperties": false,
      "description": "Always update this when you release your task, so that the agents utilize the latest code.",
      "required": [
        "Major",
        "Minor",
        "Patch"
      ],
      "properties": {
        "Major": {
          "type": "number"
        },
        "Minor": {
          "type": "number"
        },
        "Patch": {
          "type": "number"
        }
      }
    },
    "instanceNameFormat": {
      "type": "string",
      "description": "This is how the task will be displayed within the build step list - you can use variable values by using $(variablename)"
    },
    "releaseNotes": {
      "type": "string"
    },
    "inputs": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "name",
          "label",
          "type"
        ],
        "properties": {
          "name": {
            "type": "string",
            "description": "The variable name to use to store the user-supplied value",
            "pattern": "^[A-Za-z][A-Za-z0-9]*$"
          },
          "aliases": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "label": {
            "type": "string",
            "description": "The text displayed to the user for the input label"
          },
          "type": {
            "type": "string",
            "description": "The type that dictates the control rendered to the user.",
            "anyOf": [
              {
                "enum": [
                  "boolean",
                  "filePath",
                  "multiLine",
                  "pickList",
                  "radio",
                  "secureFile",
                  "string",
                  "int",
                  "identities",
                  "querycontrol"
                ]
              },
              {
                "type": "string",
                "pattern": "^connectedService\\:.+$"
              }
            ]
          },
          "defaultValue": {
            "type": [
              "string",
              "boolean"
            ],
            "description": "The default value to apply to this input."
          },
          "required": {
            "type": "boolean",
            "description": "Whether the input is a required field (default is false).",
            "default": false
          },
          "helpMarkDown": {
            "type": "string",
            "description": "Help to be displayed when hovering over the help icon for the input. To display URLs use the format [Text To Display](http://Url)"
          },
          "groupName": {
            "type": "string",
            "description": "Setting this to the name of a group defined in 'groups' will place the input into that group."
          },
          "visibleRule": {
            "type": "string",
            "description": "Allow's you to define a rule which dictates when the input will be visible to a user, for example \"variableName1 != \\\"\\\" && variableName2 = value || variableName3 NotEndsWith value\""
          },
          "properties": {
            "type": "object",
            "properties": {
              "EditableOptions": {
                "type": "string",
                "enum": [
                  "True",
                  "False"
                ]
              },
              "MultiSelect": {
                "type": "string",
                "enum": [
                  "True",
                  "False"
                ]
              },
              "MultiSelectFlatList": {
                "type": "string",
                "enum": [
                  "True",
                  "False"
                ]
              },
              "DisableManageLink": {
                "type": "string",
                "enum": [
                  "True",
                  "False"
                ]
              },
              "IsSearchable": {
                "type": "string",
                "enum": [
                  "True",
                  "False"
                ]
              },
              "PopulateDefaultValue": {
                "type": "string",
                "enum": [
                  "True",
                  "False"
                ]
              },
              "isVariableOrNonNegativeNumber": {
                "type": "string",
                "enum": [
                  "true",
                  "false"
                ]
              },
              "resizable": {
                "type": "boolean"
              },
              "rows": {
                "type": "string",
                "pattern": "^\\d+$"
              },
              "maxLength": {
                "type": "string",
                "pattern": "^\\d+$"
              },
              "editorExtension": {
                "type": "string"
              },
              "EndpointFilterRule": {
                "type": "string"
              }
            }
          },
          "options": {
            "type": "object",
            "additionalProperties": true
          }
        }
      }
    },
    "dataSourceBindings": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "target": {
            "type": "string"
          },
          "endpointId": {
            "type": "string"
          },
          "dataSourceName": {
            "type": "string"
          },
          "parameters": {
            "type": "object"
          },
          "resultTemplate": {
            "type": "string"
          },
          "endpointUrl": {
            "type": "string"
          },
          "resultSelector": {
            "type": "string"
          },
          "RequestVerb": {
            "type": "string",
            "enum": [
              "GET",
              "POST",
              "DELETE",
              "OPTIONS",
              "HEAD",
              "PUT",
              "TRACE",
              "PATCH"
            ]
          },
          "requestContent": {
            "type": "string"
          },
          "callbackContextTemplate": {
            "type": "string"
          },
          "callbackRequiredTemplate": {
            "type": "string"
          },
          "initialContextTemplate": {
            "type": "string"
          }
        }
      }
    },
    "sourceDefinitions": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "target": {
            "type": "string"
          },
          "endpoint": {
            "type": "string"
          },
          "selector": {
            "type": "string"
          },
          "keySelector": {
            "type": "string"
          },
          "authKey": {
            "type": "string"
          }
        }
      }
    },
    "prejobexecution": {
      "type": "object",
      "additionalProperties": false,
      "description": "Execution options for this task (on Pre-Job stage)",
      "properties": {
        "Node16": {
          "$ref": "#/definitions/executionObject"
        },
        "Node10": {
          "$ref": "#/definitions/executionObject"
        },
        "Node": {
          "$ref": "#/definitions/executionObject"
        },
        "PowerShell3": {
          "$ref": "#/definitions/executionObject"
        },
        "PowerShell": {
          "$ref": "#/definitions/executionObject"
        }
      }
    },
    "execution": {
      "type": "object",
      "additionalProperties": false,
      "description": "Execution options for this task",
      "properties": {
        "Node16": {
          "$ref": "#/definitions/executionObject"
        },
        "Node10": {
          "$ref": "#/definitions/executionObject"
        },
        "Node": {
          "$ref": "#/definitions/executionObject"
        },
        "PowerShell3": {
          "$ref": "#/definitions/executionObject"
        },
        "PowerShell": {
          "$ref": "#/definitions/executionObject"
        }
      }
    },
    "postjobexecution": {
      "type": "object",
      "additionalProperties": false,
      "description": "Execution options for this task (on Post-Job stage)",
      "properties": {
        "Node16": {
          "$ref": "#/definitions/executionObject"
        },
        "Node10": {
          "$ref": "#/definitions/executionObject"
        },
        "Node": {
          "$ref": "#/definitions/executionObject"
        },
        "PowerShell3": {
          "$ref": "#/definitions/executionObject"
        },
        "PowerShell": {
          "$ref": "#/definitions/executionObject"
        }
      }
    },
    "messages": {
      "type": "object"
    },
    "outputVariables": {
      "type": "array",
      "description": "Describes output variables of task.",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "type": "string",
            "description": "The variable name",
            "pattern": "^[A-Za-z][A-Za-z0-9]*$"
          },
          "description": {
            "type": "string",
            "description": "Detailed description of the variable"
          }
        }
      }
    },
    "restrictions": {
      "type": "object",
      "additionalProperties": false,
      "description": "Restrictions on tasks",
      "properties": {
        "commands": {
          "type": "object",
          "additionalProperties": false,
          "description": "Restrictions on available task commands",
          "properties": {
            "mode": {
              "type": "string",
              "enum": [
                "any",
                "restricted"
              ]
            }
          }
        },
        "settableVariables": {
          "type": "object",
          "additionalProperties": false,
          "description": "Restrictions on which variables can be set via commands",
          "properties": {
            "allowed": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "$schema": {
      "type": "string"
    }
  },
  "definitions": {
    "executionObject": {
      "type": "object",
      "additionalProperties": true,
      "required": [
          "target"
      ],
      "properties": {
        "target": {
          "type": "string",
          "description": "The target file to be executed. You can use variables here in brackets e.g. $(currentDirectory)\filename.ps1"
        },
        "platforms": {
          "type": "array",
          "items": {
            "enum": [
              "windows"
            ]
          }
        },
        "argumentFormat": {
          "type": "string"
        },
        "workingDirectory": {
          "type": "string"
        }
      }
    }
  }
}

=== microsoft/azure-pipelines-tasks/Tasks/VsTestV1/task.loc.json
{
  "id": "EF087383-EE5E-42C7-9A53-AB56C98420F9",
  "name": "VSTest",
  "friendlyName": "ms-resource:loc.friendlyName",
  "description": "ms-resource:loc.description",
  "helpUrl": "https://docs.microsoft.com/azure/devops/pipelines/tasks/test/vstest",
  "helpMarkDown": "ms-resource:loc.helpMarkDown",
  "category": "Test",
  "visibility": [
    "Build",
    "Release"
  ],
  "runsOn": [
    "Agent",
    "DeploymentGroup"
  ],
  "author": "Microsoft Corporation",
  "version": {
    "Major": 1,
    "Minor": 273,
    "Patch": 0
  },
  "demands": [
    "vstest"
  ],
  "minimumAgentVersion": "1.89.0",
  "groups": [
    {
      "name": "executionOptions",
      "displayName": "ms-resource:loc.group.displayName.executionOptions",
      "isExpanded": true
    },
    {
      "name": "advancedExecutionOptions",
      "displayName": "ms-resource:loc.group.displayName.advancedExecutionOptions",
      "isExpanded": false
    },
    {
      "name": "reportingOptions",
      "displayName": "ms-resource:loc.group.displayName.reportingOptions",
      "isExpanded": false
    }
  ],
  "deprecated": true,
  "deprecationMessage": "The VSTest@1 task is deprecated, please use the latest version of the VSTest task",
  "inputs": [
    {
      "name": "testAssembly",
      "type": "string",
      "label": "ms-resource:loc.input.label.testAssembly",
      "defaultValue": "**\\*test*.dll;-:**\\obj\\**",
      "required": true,
      "helpMarkDown": "ms-resource:loc.input.help.testAssembly",
      "groupName": "executionOptions"
    },
    {
      "name": "testFiltercriteria",
      "type": "string",
      "label": "ms-resource:loc.input.label.testFiltercriteria",
      "defaultValue": "",
      "required": false,
      "helpMarkDown": "ms-resource:loc.input.help.testFiltercriteria",
      "groupName": "executionOptions"
    },
    {
      "name": "runSettingsFile",
      "type": "filePath",
      "label": "ms-resource:loc.input.label.runSettingsFile",
      "defaultValue": "",
      "required": false,
      "helpMarkDown": "ms-resource:loc.input.help.runSettingsFile",
      "groupName": "executionOptions"
    },
    {
      "name": "overrideTestrunParameters",
      "type": "string",
      "label": "ms-resource:loc.input.label.overrideTestrunParameters",
      "defaultValue": "",
      "required": false,
      "helpMarkDown": "ms-resource:loc.input.help.overrideTestrunParameters",
      "groupName": "executionOptions"
    },
    {
      "name": "codeCoverageEnabled",
      "type": "boolean",
      "label": "ms-resource:loc.input.label.codeCoverageEnabled",
      "defaultValue": "False",
      "required": false,
      "helpMarkDown": "ms-resource:loc.input.help.codeCoverageEnabled",
      "groupName": "executionOptions"
    },
    {
      "name": "runInParallel",
      "type": "boolean",
      "label": "ms-resource:loc.input.label.runInParallel",
      "defaultValue": "false",
      "required": false,
      "helpMarkDown": "ms-resource:loc.input.help.runInParallel",
      "groupName": "executionOptions"
    },
    {
      "name": "vstestLocationMethod",
      "type": "radio",
      "label": "ms-resource:loc.input.label.vstestLocationMethod",
      "required": false,
      "groupName": "advancedExecutionOptions",
      "defaultValue": "version",
      "options": {
        "version": "Version",
        "location": "Specify Location"
      }
    },
    {
      "name": "vsTestVersion",
      "type": "pickList",
      "label": "ms-resource:loc.input.label.vsTestVersion",
      "defaultValue": "14.0",
      "required": false,
      "helpMarkDown": "ms-resource:loc.input.help.vsTestVersion",
      "groupName": "advancedExecutionOptions",
      "visibleRule": "vstestLocationMethod = version",
      "options": {
        "latest": "Latest",
        "14.0": "Visual Studio 2015",
        "12.0": "Visual Studio 2013"
      }
    },
    {
      "name": "vstestLocation",
      "type": "string",
      "label": "ms-resource:loc.input.label.vstestLocation",
      "defaultValue": "",
      "required": false,
      "helpMarkDown": "ms-resource:loc.input.help.vstestLocation",
      "visibleRule": "vstestLocationMethod = location",
      "groupName": "advancedExecutionOptions"
    },
    {
      "name": "pathtoCustomTestAdapters",
      "type": "string",
      "label": "ms-resource:loc.input.label.pathtoCustomTestAdapters",
      "defaultValue": "",
      "required": false,
      "helpMarkDown": "ms-resource:loc.input.help.pathtoCustomTestAdapters",
      "groupName": "advancedExecutionOptions"
    },
    {
      "name": "otherConsoleOptions",
      "type": "string",
      "label": "ms-resource:loc.input.label.otherConsoleOptions",
      "defaultValue": "",
      "required": false,
      "helpMarkDown": "ms-resource:loc.input.help.otherConsoleOptions",
      "groupName": "advancedExecutionOptions"
    },
    {
      "name": "testRunTitle",
      "type": "string",
      "label": "ms-resource:loc.input.label.testRunTitle",
      "defaultValue": "",
      "required": false,
      "helpMarkDown": "ms-resource:loc.input.help.testRunTitle",
      "groupName": "reportingOptions"
    },
    {
      "name": "platform",
      "type": "string",
      "label": "ms-resource:loc.input.label.platform",
      "defaultValue": "",
      "required": false,
      "helpMarkDown": "ms-resource:loc.input.help.platform",
      "groupName": "reportingOptions"
    },
    {
      "name": "configuration",
      "type": "string",
      "label": "ms-resource:loc.input.label.configuration",
      "defaultValue": "",
      "required": false,
      "helpMarkDown": "ms-resource:loc.input.help.configuration",
      "groupName": "reportingOptions"
    },
    {
      "name": "publishRunAttachments",
      "type": "boolean",
      "label": "ms-resource:loc.input.label.publishRunAttachments",
      "defaultValue": "true",
      "required": false,
      "helpMarkDown": "ms-resource:loc.input.help.publishRunAttachments",
      "groupName": "reportingOptions"
    }
  ],
  "instanceNameFormat": "ms-resource:loc.instanceNameFormat",
  "execution": {
    "PowerShell": {
      "target": "$(currentDirectory)\\VSTest.ps1",
      "argumentFormat": "",
      "workingDirectory": "$(currentDirectory)",
      "platforms": [
        "windows"
      ]
    }
  },
  "messages": {
    "PathDoesNotExist": "ms-resource:loc.messages.PathDoesNotExist",
    "VstestReturnCode": "ms-resource:loc.messages.VstestReturnCode",
    "NoMatchingTestAssemblies": "ms-resource:loc.messages.NoMatchingTestAssemblies",
    "VstestNotFound": "ms-resource:loc.messages.VstestNotFound",
    "VstestFailed": "ms-resource:loc.messages.VstestFailed",
    "VstestTIANotSupported": "ms-resource:loc.messages.VstestTIANotSupported",
    "NoResultsToPublish": "ms-resource:loc.messages.NoResultsToPublish",
    "ErrorWhileReadingRunSettings": "ms-resource:loc.messages.ErrorWhileReadingRunSettings",
    "ErrorWhileReadingTestSettings": "ms-resource:loc.messages.ErrorWhileReadingTestSettings",
    "RunInParallelNotSupported": "ms-resource:loc.messages.RunInParallelNotSupported",
    "FailedToSetRunInParallel": "ms-resource:loc.messages.FailedToSetRunInParallel",
    "UpdateOneOrHigherRequired": "ms-resource:loc.messages.UpdateOneOrHigherRequired",
    "ErrorOccuredWhileSettingRegistry": "ms-resource:loc.messages.ErrorOccuredWhileSettingRegistry",
    "ErrorWhileSettingTestImpactCollectorTestSettings": "ms-resource:loc.messages.ErrorWhileSettingTestImpactCollectorTestSettings",
    "ErrorWhileSettingTestImpactCollectorRunSettings": "ms-resource:loc.messages.ErrorWhileSettingTestImpactCollectorRunSettings",
    "ErrorWhileCreatingResponseFile": "ms-resource:loc.messages.ErrorWhileCreatingResponseFile",
    "ErrorWhileUpdatingResponseFile": "ms-resource:loc.messages.ErrorWhileUpdatingResponseFile",
    "ErrorWhilePublishingCodeChanges": "ms-resource:loc.messages.ErrorWhilePublishingCodeChanges",
    "ErrorWhileListingDiscoveredTests": "ms-resource:loc.messages.ErrorWhileListingDiscoveredTests",
    "PublishCodeChangesPerfTime": "ms-resource:loc.messages.PublishCodeChangesPerfTime",
    "GenerateResponseFilePerfTime": "ms-resource:loc.messages.GenerateResponseFilePerfTime",
    "UploadTestResultsPerfTime": "ms-resource:loc.messages.UploadTestResultsPerfTime",
    "ErrorReadingVstestVersion": "ms-resource:loc.messages.ErrorReadingVstestVersion",
    "UnexpectedVersionString": "ms-resource:loc.messages.UnexpectedVersionString",
    "UnexpectedVersionNumber": "ms-resource:loc.messages.UnexpectedVersionNumber",
    "VstestDiagNotSupported": "ms-resource:loc.messages.VstestDiagNotSupported"
  }
}

=== microsoft/azure-pipelines-tasks/Tasks/AzureKeyVault/task.json
{
    "id": "1E244D32-2DD4-4165-96FB-B7441CA9331E",
    "name": "AzureKeyVault",
    "friendlyName": "Azure Key Vault",
    "description": "Download Azure Key Vault Secrets",
    "helpMarkDown": "[More Information](https://aka.ms/azkvtaskreadme)",
    "category": "Deploy",
    "releaseNotes": "Works with Xplat agents (Windows, Linux or OSX)",
    "visibility": [
        "Build",
        "Release"
    ],
    "author": "Microsoft Corporation",
    "version": {
        "Major": 1,
        "Minor": 0,
        "Patch": 0
    },
    "demands": [],
    "minimumAgentVersion": "2.0.0",
    "inputs": [
        {
            "name": "ConnectedServiceName",
            "type": "connectedService:AzureRM",
            "label": "Azure subscription",
            "defaultValue": "",
            "required": true,
            "helpMarkDown": "Select the Azure subscription for the key vault."
        },
        {
            "name": "KeyVaultName",
            "type": "pickList",
            "label": "Key vault",
            "required": true,
            "helpMarkDown": "Provide the name of a key vault.",
            "properties": {
                "EditableOptions": "True"
            }
        },
        {
            "name": "SecretsFilter",
            "type": "string",
            "label": "Secrets filter",
            "defaultValue": "*",
            "required": true,
            "helpMarkDown": "Comma separated list of secret names or leave * to download all secrets from the selected key vault.",
            "options": {
                "EditableOptions": "True"
            }
        }
    ],
    "dataSourceBindings": [
        {
            "target": "KeyVaultName",
            "endpointId": "$(ConnectedServiceName)",
            "dataSourceName": "AzureKeyVaults"
        }
    ],
    "instanceNameFormat": "Azure Key Vault: $(KeyVaultName)",
    "execution": {
        "Node": {
            "target": "main.js"
        }
    },
    "messages": {
        "ClientIdCannotBeEmpty": "clientId must be a non empty string.",
        "DomainCannotBeEmpty": "domain must be a non empty string.",
        "SecretCannotBeEmpty": "secret must be a non empty string.",
        "armUrlCannotBeEmpty": "arm Url must be a non empty string.",
        "authorityUrlCannotBeEmpty": "authority must be a non empty string.",
        "CouldNotFetchAccessTokenforAzureStatusCode": "Could not fetch access token for azure. Status code: %s, status message: %s",
        "CallbackCannotBeNull": "callback cannot be null.",
        "CredentialsCannotBeNull": "'credentials' cannot be null.",
        "SubscriptionIdCannotBeNull": "'subscriptionId' cannot be null.",
        "InvalidResponseLongRunningOperation": "Invalid response received for fetching status of a long running operation.",
        "TimeoutWhileWaiting": "Timed out while waiting",
        "ResourceGroupCannotBeNull": "resourceGroupName cannot be null or undefined and it must be of type string.",
        "ResourceGroupExceededLength": "\"resourceGroupName\" should satisfy the constraint - \"MaxLength\": 90",
        "ResourceGroupDeceededLength": "\"resourceGroupName\" should satisfy the constraint - \"MinLength\": 1",
        "ResourceGroupDoesntMatchPattern": "\"resourceGroupName\" should satisfy the constraint - \"Pattern\": /^[-\\w\\._\\(\\)]+$/",
        "AzKv_ConstructorFailed": "Azure key vault parameters initialization failed. Error: %s.",
        "DownloadingSecretsUsing": "Downloading secrets using: %s.",
        "GetSecretsFailed": "Get secrets failed. Error: %s.",
        "NoSecretsFound": "No secrets found in: %s",
        "NumberOfSecretsFound": "Number of secrets found in %s: %s",
        "NumberOfEnabledSecretsFound": "Number of enabled and unexpired secrets found in %s: %s",
        "DownloadingSecretValue": "Downloading secret value for: %s.",
        "GetSecretValueFailed": "Get secret value failed for: %s. Error: %s.",
        "ConflictingVariableFound": "Variable with name %s is defined in both environment and key vault"
    }
}
