=== microsoft/azure-pipelines-tasks/OneLocBuild/packages/LSBuild.XLoc.7.2.20223/tools/netfx/locxml.dtd
<!ELEMENT	_locDefinition (_locDefault?, _locDefaultAttr?, _locTag*)>

<!ELEMENT 	_locDefault EMPTY>
<!ATTLIST	_locDefault _loc (locNone|locData|locFull)	"locData"
			_locEntity CDATA #IMPLIED
			_locID (useID|strict) "strict">

<!ELEMENT 	_locDefaultAttr EMPTY>
<!ATTLIST	_locDefaultAttr _loc (locNone|locData)	"locNone">

<!ELEMENT 	_locTag (#PCDATA)>
<!ATTLIST	_locTag	_loc (locNone|locData|locFull)	"locNone"
			_locIDAttr CDATA #IMPLIED			
			_locAttrData CDATA #IMPLIED>

=== microsoft/azure-pipelines-tasks/OneLocBuild/packages/LSBuild.XLoc.7.2.20223/tools/netfx/locxml_VSfeed.xml
<?xml version="1.0"?>
<!DOCTYPE _locDefinition SYSTEM "locXML.dtd">
<_locDefinition>
    <_locDefault _loc="locNone"/>
    <_locTag _loc="locData">title</_locTag>
    <_locTag _loc="locData">description</_locTag>
    <_locTag _loc="locData">summary</_locTag>
    <_locTag _loc="locData">longSummary</_locTag>
    <!--<_locTag _loc="locData">languageId</_locTag> remove "languageId" from lsbuild loc process-->
    <_locTag _loc="locData">culture</_locTag>
<!--new-->
    <_locTag _loc="locData">Title</_locTag>
    <_locTag _loc="locData">Description</_locTag>
    <_locTag _loc="locData">Name</_locTag>
    <_locTag _loc="locData">detailedInformation</_locTag>
    <_locTag _loc="locData">SubfolderDisplayName</_locTag>
    <_locTag _loc="locData">DisplayName</_locTag>
    <_locTag _loc="locData">policy</_locTag>
        <_locTag _loc="locData">buttonToolTip</_locTag>
        <_locTag _loc="locData">buttonText</_locTag>
<!-- adding new tag for loc for dynamic feed link tag-->
    <_locTag _loc="locData" _locIDAttr="rel" _locAttrData="href">link</_locTag>

</_locDefinition>

=== microsoft/azure-pipelines-tasks/OneLocBuild/packages/LSBuild.XLoc.7.2.20224/tools/netfx/locxml_Apollo.xml
<?xml version="1.0"?>
<!DOCTYPE _locDefinition SYSTEM "locXML.dtd">

<!-- 
	REVISION HISTORY:
-->

<_locDefinition>
<_locDefault _loc="locNone"/>

	<_locTag _loc="locData" _locAttrData="DisplayName" _locIDAttr="Name">Category</_locTag>
	<_locTag _loc="locData" _locAttrData="DisplayName, Description" _locIDAttr="Name">StringListProperty</_locTag>
	<_locTag _loc="locData" _locAttrData="DisplayName, Description" _locIDAttr="Name">StringProperty</_locTag>
	<_locTag _loc="locData" _locAttrData="DisplayName, Description" _locIDAttr="Name">EnumProperty</_locTag>
	<_locTag _loc="locData" _locAttrData="DisplayName, Description" _locIDAttr="Name">EnumValue</_locTag>
	<_locTag _loc="locData" _locAttrData="DisplayName, Description" _locIDAttr="Name">BoolProperty</_locTag>
	<_locTag _loc="locData" _locAttrData="DisplayName, Description" _locIDAttr="Name">ValueEditor</_locTag>
	<_locTag _loc="locData" _locAttrData="DisplayName, Description" _locIDAttr="Name">IntProperty</_locTag>
	<_locTag _loc="locData" _locAttrData="DisplayName, Description" _locIDAttr="Name">DynamicEnumProperty</_locTag>
	  <_locTag _loc="locData" _locAttrData="DisplayName, Description" _locIDAttr="Name">Rule</_locTag>
	  <_locTag _loc="locData" _locAttrData="Name" _locIDAttr="id">Command</_locTag>
	  <_locTag _loc="locData" _locAttrData="xml:lang" _locIDAttr="version">grammar</_locTag>
	  <_locTag _loc="locData" _locAttrData="xml:lang">CommandSet</_locTag>
	  <_locTag _loc="locData" _locAttrData="(XMLComments)">!--</_locTag>
	  <_locTag _loc="locData" >item</_locTag>
	  <_locTag _loc="locData" >Item</_locTag>
	  <_locTag _loc="locData" >Example</_locTag>
	  <_locTag _loc="locData" >ListenFor</_locTag>
	  <_locTag _loc="locData" >Feedback</_locTag>
	  <_locTag _loc="locData" >CommandPrefix</_locTag>
	  </_locDefinition>

=== microsoft/azure-pipelines-tasks/OneLocBuild/packages/LSBuild.XLoc.7.2.20231/tools/netfx/locxml_CRM_Mainline.xml
<?xml version="1.0"?>
<!DOCTYPE _locDefinition SYSTEM "locXML.dtd">
<_locDefinition>
	<!-- To Do: uncomment following line to set elements as none-localizable by default -->
	<!-- <_locDefault _loc="locNone"/> -->
	<!-- To Do: uncomment following line to set all attributes to localizable by default -->
	<!-- <_locDefaultAttr _loc="locData"/> -->

	<!-- To Do: uncomment following line to set tag test to none-localizable 

		and its attributes size and type to localizable.
	        The _locIDAttr is optional and defines the id-attribute as the 
		resource id to use in place of a _locID attribute. 
		For eg: the value of the 'name' attribute of the 'test' tag will be 
		treated as the id for all the localizable content of the 'test' tag.
		-->
	<!-- <_locTag _loc="locNone" _locIDAttr="name" _locAttrData="size,type">test</_locTag> -->
	<_locDefault _loc="locNone"/>

	<_locTag _loc="locData" _locAttrData="label, helperText" _locIDAttr="id">group</_locTag>
	<_locTag _loc="locData" _locAttrData="label, description" _locIDAttr="id">tab</_locTag>
	<_locTag _loc="locData" _locAttrData="description, label, screentip, supertip,keytip" _locIDAttr="id">button</_locTag>
	<_locTag _loc="locData" _locAttrData="label, screentip, supertip" _locIDAttr="id">dynamicMenu</_locTag>
	<_locTag _loc="locData" _locAttrData="label, screentip, supertip" _locIDAttr="id">menu</_locTag>
	<_locTag _loc="locData" _locAttrData="label, description" _locIDAttr="id">task</_locTag>
	<_locTag _loc="locData" _locAttrData="label, description" _locIDAttr="id">taskGroup</_locTag>
	<_locTag _loc="locData" _locAttrData="label" _locIDAttr="id">dropDown</_locTag>
	<_locTag _loc="locData" _locAttrData="keytip">control</_locTag>

	<!-- To Do: uncomment following line to set tag bold to fully-localizable  -->
	<!-- <_locTag _loc="locFull">bold</_locTag> -->
</_locDefinition>

=== microsoft/azure-pipelines-tasks/OneLocBuild/packages/LSBuild.XLoc.7.2.20223/tools/netfx/locxml_WiXXSD.xml
<?xml version="1.0"?>
<!DOCTYPE _locDefinition SYSTEM "locXML.dtd">
<_locDefinition>
	<!-- To Do: uncomment following line to set elements as none-localizable by default -->
	<_locDefault _loc="locNone"/>
	<_locDefaultAttr _loc="locNone"/>
	<!-- To Do: uncomment following line to set all attributes to localizable by default -->
	<!-- <_locDefaultAttr _loc="locData"/> -->

	<!-- To Do: uncomment following line to set tag test to none-localizable 

		and its attributes size and type to localizable.
			The _locIDAttr is optional and defines the id-attribute as the 
		resource id to use in place of a _locID attribute. 
		For eg: the value of the 'name' attribute of the 'test' tag will be 
		treated as the id for all the localizable content of the 'test' tag.
		-->
	<!-- <_locTag _loc="locNone" _locIDAttr="name" _locAttrData="size,type">test</_locTag> -->
        <!-- <_locTag _loc="locNone" _locAttrData="href">xse:msiRef</_locTag> -->


	<!-- To Do: uncomment following line to set tag bold to fully-localizable  -->
	<!-- <_locTag _loc="locFull">bold</_locTag> -->
	<_locTag _loc="locData">xs:documentation</_locTag>
	<_locTag _loc="locFull">html:a</_locTag>
	<_locTag _loc="locData">html:ul</_locTag>
	<_locTag _loc="locData">html:li</_locTag>
	<_locTag _loc="locData">html:ol</_locTag>
	<_locTag _loc="locData">html:dl</_locTag>
	<_locTag _loc="locData">html:dd</_locTag>
	<_locTag _loc="locData">html:dt</_locTag>
	<_locTag _loc="locData">html:b</_locTag>
	<_locTag _loc="locNone">html:br</_locTag>
	<_locTag _loc="locData">html:dfn</_locTag>
</_locDefinition>

=== microsoft/azure-pipelines-tasks/OneLocBuild/packages/LSBuild.XLoc.7.2.20222/tools/netfx/locxml_snippets.xml
<?xml version="1.0"?>
<!DOCTYPE _locDefinition SYSTEM "locXML.dtd">

<!-- 
	REVISION HISTORY:
-->

<_locDefinition>

	<!-- Snippets files -->
	<_locTag _loc="locNone">Assembly</_locTag>
	<_locTag _loc="locNone">Author</_locTag>
	<_locTag _loc="locNone">Code</_locTag>
	<_locTag _loc="locNone">Default</_locTag>
	<_locTag _loc="locNone">ID</_locTag>
	<_locTag _loc="locNone">Literal</_locTag>
	<_locTag _loc="locNone">Namespace</_locTag>
	<_locTag _loc="locNone">Object</_locTag>
	<_locTag _loc="locNone">Shortcut</_locTag>
	<_locTag _loc="locNone">SnippetType</_locTag>
	<_locTag _loc="locNone">Type</_locTag>
	<_locTag _loc="locNone">Version</_locTag>
	<_locTag _loc="locNone">Function</_locTag>

	<!-- Snippets Index files -->
	<_locTag _loc="locNone">DirPath</_locTag>
	<_locTag _loc="locNone">Installed</_locTag>
	<_locTag _loc="locNone">OnOff</_locTag>


</_locDefinition>

=== microsoft/azure-pipelines-tasks/OneLocBuild/packages/LSBuild.XLoc.7.2.20223/tools/netfx/NTDEV_locXML.xml
<?xml version="1.0"?>
<!DOCTYPE _locDefinition SYSTEM "locxml.dtd">
<_locDefinition>
	<!-- this is generated from optionSet -->
  <_locDefault _loc="locData" _locID="strict"></_locDefault><!--  -->
  
  <_locTag _loc="locData" _locAttrData="DIR">HTML</_locTag> <!-- ieframe.dll.mui shdocvw.dll.mui --> 
	<_locTag _loc="locFull">Text</_locTag>                    <!-- ehres.dll.mui -->
	<_locTag _loc="locData" _locAttrData="align">td</_locTag> <!-- tracerpt.exe.mui ws03res.dll.mui -->
	<_locTag _loc="locData" _locAttrData="*">title</_locTag>  <!-- bootmgr.efi.mui tracerpt.exe.mui -->
	<_locTag _loc="locFull">b</_locTag>                       <!-- tracerpt.exe.mui -->
	<_locTag _loc="locFull">img</_locTag>                     <!-- ieframe.dll.mui rssexplorerframe.dll.mui ws03res.dll.mui -->
	<_locTag _loc="locFull">ul</_locTag>                      <!-- tracerpt.exe.mui -->
	<_locTag _loc="locFull">li</_locTag>                      <!-- ptres.dll.mui -->
	<_locTag _loc="locFull">br</_locTag>                      <!-- bootmgr.efi.mui ptres.dll.mui tracerpt.exe.mui -->
	<_locTag _loc="locData" _locAttrData="xmlns">Name</_locTag> <!-- GameDefinitionFile.dll -->
	<_locTag _loc="locNone">meta</_locTag>	<!-- *.wpl  WMP playlist files --> 
	<_locTag _loc="locNone">sourceFilter</_locTag>	<!-- *.wpl  WMP playlist files --> 
	<_locTag _loc="locNone">fragment</_locTag>	<!-- *.wpl  WMP playlist files --> 
	<_locTag _loc="locNone">argument</_locTag>	<!-- *.wpl  WMP playlist files --> 
	<_locTag _loc="locNone" _locAttrData="">ConsoleFileID</_locTag>	<!-- *.msc files -->
	<_locTag _loc="locNone" _locAttrData="">Binary</_locTag>		<!-- *.msc files -->
	<_locTag _loc="locNone" _locAttrData="">GUID</_locTag>		<!-- *.msc files -->
	<_locTag _loc="locData" _locIDAttr="ID">String</_locTag>   <!-- *.msc and .plaxml files -->
    <_locTag _loc="locData" _locIDAttr="ID">String</_locTag>   <!-- *.wxl files -->
	<_locTag _loc="locData" _locIDAttr="id" _locAttrData="value">string</_locTag>   <!-- *.adml files , *.mum files also require ' _locAttrData="value" ' -->
	<_locTag _loc="locData" _locIDAttr="id">presentation</_locTag>   <!-- .adml files -->
	<_locTag _loc="locData" _locIDAttr="refId">listBox</_locTag>   <!-- .adml files -->
	<_locTag _loc="locData" _locIDAttr="refId">checkBox</_locTag>   <!-- .adml files -->
	<_locTag _loc="locData" _locIDAttr="refId">dropdownList</_locTag>   <!-- .adml files -->
	<_locTag _loc="locData" _locIDAttr="refId">decimalTextBox</_locTag>   <!-- .adml files -->
	<_locTag _loc="locData" _locIDAttr="name">Title</_locTag>   <!-- tracerpt.exe.mui -->
	<_locTag _loc="locData" _locAttrData="tip">option</_locTag>   <!-- memtest.*.mui winload.*.mui winldfw.efi.mui -->
	<_locTag _loc="locData" _locAttrData="displayName,description">update</_locTag>  <!-- *.mum files -->
	<_locTag _loc="locData" _locAttrData="displayName,description">assembly</_locTag>  <!-- *.mum files -->
	<_locTag _loc="locData" _locAttrData="PostInstallDescription,PostUninstallDescription">PostDeploymentInfo</_locTag>  <!-- *.mum files -->
	<_locTag _loc="locData" _locIDAttr="id">resource</_locTag>
	<_locTag _loc="locFull">ref</_locTag> 
	<_locTag _loc="locFull">str</_locTag> 
	<_locTag _loc="locData" _locIDAttr="id" _locAttrData="name,abbrev">day</_locTag>
	<_locTag _loc="locData" _locIDAttr="id" _locAttrData="name,abbrev">month</_locTag>
	<_locTag _loc="locData" _locAttrData="DisplayName,Description"> ServerComponent</_locTag>  <!-- *.mum files -->

  <!-- not used anymore
  <_locTag _loc="locFull" _locAttrData="">Property</_locTag>
  <_locTag _loc="locFull" _locAttrData="">ToolTip</_locTag>
  <_locTag _loc="locFull" _locAttrData="">Name</_locTag>
  <_locTag _loc="locFull" _locAttrData="">Value</_locTag>
  <_locTag _loc="locData" _locAttrData="VALUE">LANGUAGE</_locTag>
  <_locTag _loc="locData" _locAttrData="DISPLAYNAME">SKU</_locTag>
  <_locTag _loc="locData" _locAttrData="ACCESSKEY">BUTTON</_locTag>
  <_locTag _loc="locData" _locAttrData="String">Segment</_locTag>
  <_locTag _loc="locData" _locAttrData="Title,Description">NODE</_locTag>
  <_locTag _loc="locData" _locAttrData="style">tr</_locTag>
  <_locTag _loc="locData" _locAttrData="Width">Label</_locTag>
  <_locTag _loc="locData" _locAttrData="Width">Control</_locTag>
  <_locTag _loc="locData" _locAttrData="*">mys</_locTag>
  <_locTag _loc="locData" _locAttrData="title, nodata,roledescription,nodatadescription">task</_locTag>
  <_locTag _loc="locData" _locAttrData="name, tooltip">subtask</_locTag>
  <_locTag _loc="locData" _locAttrData="name,link,tooltip">tool</_locTag>
  <_locTag _loc="locData" _locAttrData="title">tooltray</_locTag>
  <_locTag _loc="locData" _locAttrData="Name,RefName">ProcessMatchingCriteria</_locTag>
  <_locTag _loc="locData" _locAttrData="Name">AllocationCriteria</_locTag>
  <_locTag _loc="locData" _locAttrData="Name">Policy</_locTag>
  <_locTag _loc="locFull" _locAttrData="">u</_locTag>
  <_locTag _loc="locFull" _locAttrData="">ol</_locTag>
  <_locTag _loc="locData" _locAttrData="GUIName">Group</_locTag>
  <_locTag _loc="locData" _locAttrData="GUIName">Component</_locTag>
  <_locTag _loc="locData" _locAttrData="description,displayName">update</_locTag>
  -->
</_locDefinition>

=== microsoft/azure-pipelines-tasks/OneLocBuild/packages/LSBuild.XLoc.7.2.20223/tools/netfx/locxml_VB.xml
<?xml version="1.0"?>
<!DOCTYPE _locDefinition SYSTEM "locXML.dtd">

<!-- 
	REVISION HISTORY:
-->

<_locDefinition>

	
	<!-- VB: DefaultContent.xml -->
	<_locTag _loc="locNone">Context</_locTag>
	<_locTag _loc="locNone">ContentAuthor</_locTag>
	<_locTag _loc="locNone">ContentID</_locTag>
	<_locTag _loc="locNone">ContentFileVersion</_locTag>
	<_locTag _loc="locNone">Exception</_locTag>
	<_locTag _loc="locNone">Type</_locTag>
	<_locTag _loc="locNone">Demand</_locTag>
	<_locTag _loc="locNone">Precondition</_locTag>

</_locDefinition>

=== microsoft/azure-pipelines-tasks/OneLocBuild/packages/LSBuild.XLoc.7.2.20223/tools/netfx/locxml_xaml_vc.xml
<?xml version="1.0"?>
<!DOCTYPE _locDefinition SYSTEM "locXML.dtd">
<_locDefinition>
	
	<!-- For VC XAML test  -->
  <_locTag _loc="locNone" _locIDAttr="Name" _locAttrData="DisplayName,Description">Rule</_locTag>
  <_locTag _loc="locNone" _locIDAttr="Name" _locAttrData="DisplayName,Description">Category</_locTag>
  <_locTag _loc="locNone" _locIDAttr="Name" _locAttrData="DisplayName,Description">StringProperty</_locTag>
  <_locTag _loc="locNone" _locIDAttr="Name" _locAttrData="DisplayName,Description">BoolProperty</_locTag>
  <_locTag _loc="locNone" _locIDAttr="Name" _locAttrData="DisplayName,Description">StringListProperty</_locTag>
  <_locTag _loc="locNone" _locIDAttr="Name" _locAttrData="DisplayName,Description">EnumProperty</_locTag>
  <_locTag _loc="locNone" _locIDAttr="Name" _locAttrData="DisplayName,Description">EnumValue</_locTag>
  <_locTag _loc="locNone" _locIDAttr="Name" _locAttrData="DisplayName,Description">ValueEditor</_locTag>
  <_locTag _loc="locNone" _locIDAttr="Name" _locAttrData="DisplayName,Description">ItemType</_locTag>
  <_locTag _loc="locNone" _locIDAttr="Name" _locAttrData="DisplayName,Description">ContentType</_locTag>
  <_locTag _loc="locNone" _locIDAttr="Name" _locAttrData="DisplayName,Description">DynamicEnumProperty</_locTag>

	<!-- For MPI Debugger XAML  -->
  <_locTag _loc="locNone" _locIDAttr="Name" _locAttrData="DisplayName,Description">IntProperty</_locTag>
</_locDefinition>
