=== microsoft/azure-pipelines-tasks/OneLocBuild/packages/LSBuild.XLoc.7.2.20223/tools/netfx/locxml.dtd
<!ELEMENT	_locDefinition (_locDefault?, _locDefaultAttr?, _locTag*)>

<!ELEMENT 	_locDefault EMPTY>
<!ATTLIST	_locDefault _loc (locNone|locData|locFull)	"locData"
			_locEntity CDATA #IMPLIED
			_locID (useID|strict) "strict">

<!ELEMENT 	_locDefaultAttr EMPTY>
<!ATTLIST	_locDefaultAttr _loc (locNone|locData)	"locNone">

<!ELEMENT 	_locTag (#PCDATA)>
<!ATTLIST	_locTag	_loc (locNone|locData|locFull)	"locNone"
			_locIDAttr CDATA #IMPLIED			
			_locAttrData CDATA #IMPLIED>

=== microsoft/azure-pipelines-tasks/OneLocBuild/packages/LSBuild.XLoc.7.2.20224/tools/netfx/locxml_intellisense.xml
<?xml version="1.0"?>
<!DOCTYPE _locDefinition SYSTEM "locXML.dtd">
<_locDefinition>
    <_locDefault _loc="locNone"/>
    <_locTag _loc="locData">title</_locTag>
    <_locTag _loc="locData">description</_locTag>
    <_locTag _loc="locData">summary</_locTag>
    <_locTag _loc="locData">id</_locTag>
    <_locTag _loc="locData">licenseUrl</_locTag>
    <_locTag _loc="locData">projectUrl</_locTag>
    <_locTag _loc="locData">language</_locTag>
    <_locTag _loc="locData">returns</_locTag>
    <_locTag _loc="locData">param</_locTag>
  </_locDefinition>

=== microsoft/azure-pipelines-tasks/OneLocBuild/packages/LSBuild.XLoc.7.2.20223/tools/netfx/locxml_startpage.xml
<?xml version="1.0"?>
<!DOCTYPE _locDefinition SYSTEM "locXML.dtd">
<_locDefinition>
	<!-- To Do: uncomment following line to set elements as none-localizable by default -->
	<!-- <_locDefault _loc="locNone"/> -->
	<!-- To Do: uncomment following line to set all attributes to localizable by default -->
	<!-- <_locDefaultAttr _loc="locData"/> -->

	<!-- To Do: uncomment following line to set tag test to none-localizable 
		and its attributes size and type to localizable -->
	<!-- To Do: uncomment following line to set tag bold to fully-localizable  -->
	<!-- <_locTag _loc="locFull">bold</_locTag> -->

	<!-- Start Page StartPage.xaml localization -->	
	<_locTag _loc="locData" _locIDAttr="x:Uid">sys:String</_locTag> 
	<_locTag _loc="locData" _locIDAttr="x:Uid" _locAttrData="Text">TextBlock</_locTag>
	<_locTag _loc="locData" _locIDAttr="x:Uid" _locAttrData="Content">Button</_locTag>

        <!-- Start Page Links.xml localization -->	
        <_locTag _loc="locData" _locAttrData="title" _locIDAttr="id">itemsubgroup</_locTag>
        <_locTag _loc="locData" _locIDAttr="id">title</_locTag>
        <_locTag _loc="locData" _locIDAttr="id">description</_locTag>
        <_locTag _loc="locData" _locIDAttr="id">discovertitle</_locTag>
        <_locTag _loc="locData" _locIDAttr="id">discovertext</_locTag>
        <_locTag _loc="locData" _locIDAttr="id">discovernothanks</_locTag>
        <_locTag _loc="locData" _locIDAttr="id">whatsnewtitle</_locTag>
        <_locTag _loc="locData" _locIDAttr="id">gettingstartedtitle</_locTag>

</_locDefinition>
