=== microsoft/azure-pipelines-tasks/tasks.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "VSTS Tasks schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string",
      "description": "A unique guid for this task",
      "pattern": "^[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}$"
    },
    "name": {
      "type": "string",
      "description": "Name with no spaces",
      "pattern": "^[A-Za-z0-9\\-]+$"
    },
    "friendlyName": {
      "type": "string",
      "description": "Descriptive name (spaces allowed)"
    },
    "description": {
      "type": "string",
      "description": "Detailed description of what your task does"
    },
    "helpMarkDown": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "visibility": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Build",
          "Release",
          "Preview"
        ]
      }
    },
    "runsOn": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Agent",
          "MachineGroup",
          "Server"
        ]
      }
    },
    "category": {
      "type": "string",
      "description": "Where the task appears in VSTS",
      "enum": [
        "Build",
        "Utility",
        "Test",
        "Package",
        "Deploy"
      ]
    },
    "groups": {
      "type": "array",
      "description": "Describes groups that task properties may be logically grouped by in the UI.",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "name",
          "displayName"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "displayName": {
            "type": "string"
          },
          "isExpanded": {
            "type": "boolean"
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
                "Preview"
              ]
            }
          }
        }
      }
    },
    "demands": {
      "type": "array",
      "description": "Allows you to define a list of demands that a build agent requires to run this build task.",
      "items": {
        "type": "string"
      }
    },
    "minimumAgentVersion": {
      "type": "string",
      "pattern": "^\\d+\\.\\d+(\\.\\d+)?$"
    },
    "version": {
      "type": "object",
      "additionalProperties": false,
      "description": "Always update this when you release your task, so that the agents utilise the latest code.",
      "required": [
        "Major",
        "Minor",
        "Patch"
      ],
      "properties": {
        "Major": {
          "type": "number"
        },
        "Minor": {
          "type": [
            "number",
            "string"
          ]
        },
        "Patch": {
          "type": [
            "number",
            "string"
          ]
        }
      }
    },
    "instanceNameFormat": {
      "type": "string",
      "description": "This is how the task will be displayed within the build step list - you can use variable values by using $(variablename)"
    },
    "inputs": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "name",
          "label",
          "type"
        ],
        "properties": {
          "name": {
            "type": "string",
            "description": "The variable name to use to store the user-supplied value",
            "pattern": "^[A-Za-z][A-Za-z0-9]*$"
          },
          "label": {
            "type": "string",
            "description": "The text displayed to the user for the input label"
          },
          "type": {
            "type": "string",
            "description": "The type that dictates the control rendered to the user.",
            "enum": [
              "boolean",
              "connectedService:ServiceType",
              "connectedService:AzureRM",
              "connectedService:Azure",
              "connectedService:Azure:Certificate,UsernamePassword",
              "connectedService:Chef",
              "connectedService:ssh",
              "connectedService:Generic",
              "connectedService:Jenkins",
              "connectedService:servicefabric",
              "filePath",
              "multiLine",
              "pickList",
              "radio",
              "string"
            ]
          },
          "defaultValue": {
            "type": [
              "string",
              "boolean"
            ],
            "description": "The default value to apply to this input."
          },
          "required": {
            "type": "boolean",
            "description": "Whether the input is a required field (default is false).",
            "default": false
          },
          "helpMarkDown": {
            "type": "string",
            "description": "Help to be displayed when hovering over the help icon for the input. To display URLs use the format [Text To Display](http://Url)"
          },
          "groupName": {
            "type": "string",
            "description": "Setting this to the name of a group defined in 'groups' will place the input into that group."
          },
          "visibleRule": {
            "type": "string",
            "description": "Allow's you to define a rule which dictates when the input will be visible to a user, for example \"variableName = value\""
          },
          "properties": {
            "type": "object",
            "properties": {
              "EditableOptions": {
                "type": "string",
                "enum": [
                  "True",
                  "False"
                ]
              }
            }
          },
          "options": {
            "type": "object",
            "additionalProperties": true
          }
        }
      }
    },
    "dataSourceBindings": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "target": {
            "type": "string"
          },
          "endpointId": {
            "type": "string"
          },
          "dataSourceName": {
            "type": "string"
          },
          "parameters": {
            "type": "object"
          },
          "resultTemplate": {
            "type": "string"
          }
        }
      }
    },
    "sourceDefinitions": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "target": {
            "type": "string"
          },
          "endpoint": {
            "type": "string"
          },
          "selector": {
            "type": "string"
          },
          "keySelector": {
            "type": "string"
          },
          "authKey": {
            "type": "string"
          }
        }
      }
    },
    "execution": {
      "type": "object",
      "additionalProperties": false,
      "description": "Execution options for this task",
      "properties": {
        "Node": {
          "$ref": "#/definitions/executionObject"
        },
        "Bash": {
          "$ref": "#/definitions/executionObject"
        },
        "AzurePowerShell": {
          "$ref": "#/definitions/executionObject"
        },
        "PowerShell": {
          "$ref": "#/definitions/executionObject"
        },
        "PowerShell3": {
          "$ref": "#/definitions/executionObject"
        },
        "PowerShellExe": {
          "$ref": "#/definitions/executionObject"
        },
        "Process": {
          "$ref": "#/definitions/executionObject"
        },
        "RM:ManualIntervention": {
          "$ref": "#/definitions/executionObject"
        }
      }
    },
    "messages": {
      "type": "object"
    },
    "$schema": {
      "type": "string"
    }
  },
  "definitions": {
    "executionObject": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "target": {
          "type": "string",
          "description": "The target file to be executed. You can use variables here in brackets e.g. $(currentDirectory)\filename.ps1"
        },
        "argumentFormat": {
          "type": "string"
        },
        "workingDirectory": {
          "type": "string",
          "description": "The directory to execute the task from e.g. $(currentDirectory)"
        },
        "modifyEnvironment": {
          "type": [
            "boolean",
            "string"
          ]
        },
        "platforms": {
          "type": "array",
          "items": {
            "enum": [
              "windows"
            ]
          }
        }
      }
    }
  }
}

=== microsoft/azure-pipelines-tasks/Tasks/SonarQubePreBuild/task.loc.json
{
  "id": "EAE5B2CC-AC5E-4CBA-B022-A06621F9C01F",
  "name": "SonarQubePreBuild",
  "friendlyName": "ms-resource:loc.friendlyName",
  "description": "ms-resource:loc.description",
  "helpMarkDown": "ms-resource:loc.helpMarkDown",
  "category": "Build",
  "visibility": [
    "Build"
  ],
  "author": "Microsoft Corporation",
  "version": {
    "Major": 1,
    "Minor": 0,
    "Patch": 38
  },
  "demands": [
    "msbuild",
    "java"
  ],
  "groups": [
    {
      "name": "serverSettings",
      "displayName": "ms-resource:loc.group.displayName.serverSettings",
      "isExpanded": true
    },
    {
      "name": "project",
      "displayName": "ms-resource:loc.group.displayName.project",
      "isExpanded": true
    },
    {
      "name": "dbSettings",
      "displayName": "ms-resource:loc.group.displayName.dbSettings",
      "isExpanded": false
    },
    {
      "name": "advanced",
      "displayName": "ms-resource:loc.group.displayName.advanced",
      "isExpanded": false
    }
  ],
  "inputs": [
    {
      "name": "projectKey",
      "type": "string",
      "label": "ms-resource:loc.input.label.projectKey",
      "required": true,
      "helpMarkDown": "ms-resource:loc.input.help.projectKey",
      "groupName": "project"
    },
    {
      "name": "projectName",
      "type": "string",
      "label": "ms-resource:loc.input.label.projectName",
      "required": true,
      "helpMarkDown": "ms-resource:loc.input.help.projectName",
      "groupName": "project"
    },
    {
      "name": "projectVersion",
      "type": "string",
      "label": "ms-resource:loc.input.label.projectVersion",
      "defaultValue": "1.0",
      "required": true,
      "helpMarkDown": "ms-resource:loc.input.help.projectVersion",
      "groupName": "project"
    },
    {
      "name": "connectedServiceName",
      "type": "connectedService:Generic",
      "label": "ms-resource:loc.input.label.connectedServiceName",
      "required": true,
      "helpMarkDown": "ms-resource:loc.input.help.connectedServiceName",
      "groupName": "serverSettings"
    },
    {
      "name": "dbUrl",
      "type": "string",
      "label": "ms-resource:loc.input.label.dbUrl",
      "required": false,
      "helpMarkDown": "ms-resource:loc.input.help.dbUrl",
      "groupName": "dbSettings"
    },
    {
      "name": "dbUsername",
      "type": "string",
      "label": "ms-resource:loc.input.label.dbUsername",
      "required": false,
      "helpMarkDown": "ms-resource:loc.input.help.dbUsername",
      "groupName": "dbSettings"
    },
    {
      "name": "dbPassword",
      "type": "string",
      "label": "ms-resource:loc.input.label.dbPassword",
      "required": false,
      "helpMarkDown": "ms-resource:loc.input.help.dbPassword",
      "groupName": "dbSettings"
    },
    {
      "name": "cmdLineArgs",
      "type": "string",
      "label": "ms-resource:loc.input.label.cmdLineArgs",
      "required": false,
      "helpMarkDown": "ms-resource:loc.input.help.cmdLineArgs",
      "groupName": "advanced"
    },
    {
      "name": "configFile",
      "type": "filePath",
      "defaultValue": "",
      "label": "ms-resource:loc.input.label.configFile",
      "required": false,
      "helpMarkDown": "ms-resource:loc.input.help.configFile",
      "groupName": "advanced"
    },
    {
      "name": "breakBuild",
      "type": "boolean",
      "defaultValue": "",
      "label": "ms-resource:loc.input.label.breakBuild",
      "required": false,
      "helpMarkDown": "ms-resource:loc.input.help.breakBuild",
      "groupName": "advanced"
    }
  ],
  "instanceNameFormat": "ms-resource:loc.instanceNameFormat",
  "execution": {
    "PowerShell": {
      "target": "$(currentDirectory)\\SonarQubePreBuild.ps1",
      "argumentFormat": "",
      "workingDirectory": "$(currentDirectory)"
    }
  }
}

=== microsoft/azure-pipelines-tasks/Tasks/MavenPreview/task.json
{
    "id": "B8C7DDE3-ACA0-4D27-B1EF-259806BC31B6",
    "name": "MavenCC",
    "friendlyName": "Maven With CodeCoverage",
    "description": "Build with Apache Maven and check CodeCoverage",
    "helpMarkDown": "[More Information](http://go.microsoft.com/fwlink/?LinkID=624541)",
    "category": "Build",
    "visibility": [
                "Preview",
                "Build"
                  ],    
    "author": "Microsoft Corporation",
    "version": {
        "Major": 1,
        "Minor": 0,
        "Patch": 1
    },
    "demands" : [
        "maven"
    ],
    "minimumAgentVersion": "1.88.0",
    "instanceNameFormat": "MavenCC $(mavenPOMFile)",
    "groups": [
        {
            "name":"junitTestResults",
            "displayName":"JUnit Test Results",
            "isExpanded":true
        },
        {
            "name": "codeCoverage",
            "displayName": "Code Coverage",
            "isExpanded": true
        },
        {
            "name":"advanced",
            "displayName":"Advanced",
            "isExpanded":false
        }
    ],
    "inputs": [
        { 
            "name": "mavenPOMFile", 
            "type": "filePath", 
            "label": "Maven POM file", 
            "defaultValue": "", 
            "required": true,
            "helpMarkDown": "Relative path from the repo root to the `Maven POM file`."
        },
        { 
            "name": "options", 
            "type": "string", 
            "label": "Options", 
            "defaultValue": "", 
            "required": false,
            "helpMarkDown": "Specify any commandline options to be passed to Maven."
        },
        { 
            "name": "goals",
            "type": "string", 
            "label": "Goal(s)", 
            "defaultValue": "package", 
            "required": false,
            "helpMarkDown": "Specify the name of the goal to be invoked by Maven."
        },        
        {
            "name":"publishJUnitResults",
            "type":"boolean",
            "label":"Publish to VSO/TFS",
            "required":true,
            "defaultValue":"true",
            "groupName":"junitTestResults",
            "helpMarkDown":"Select this option to publish JUnit Test results produced by the Maven build to VSO/TFS. Each test result file matching `Test Results Files` will be published as a test run in VSO/TFS."
        }, 
        {
            "name": "testResultsFiles",
            "type": "filePath",
            "label": "Test Results Files",
            "defaultValue": "**/TEST-*.xml",
            "required": true,
            "groupName":"junitTestResults",
            "helpMarkDown": "Test results files path.  Wildcards can be used.  For example, `**/TEST-*.xml` for all xml files whose name starts with TEST-."
        },
        {
            "name": "codeCoverageTool",
            "type": "pickList",
            "label": "CodeCoverage Tool",
            "required": false,
            "groupName": "codeCoverage",
            "defaultValue": "None",
            "helpMarkDown": "Select the code coverage tool.",
            "options": {
                "NoCoverage": "None",
                "JaCoCo": "JaCoCo"
            }
        },
        {
            "name": "classFilter",
            "type": "string",
            "label": "Class Inclusion/Exclusion Filters",
            "defaultValue": "",
            "required": false,
            "groupName": "codeCoverage",
            "helpMarkDown": "Comma separated list of filters to include or exclude classes from collecting code coverage. For example, +:com.*,+:org.*,-:my.app*.*. Refer http://www.eclemma.org/jacoco/trunk/doc/maven.html.",
            "visibleRule": "codeCoverageTool = JaCoCo"
        },
        {
            "name":"jdkVersion",
            "type":"pickList",
            "label":"JDK Version",
            "required":false,
            "groupName":"advanced",
            "defaultValue":"default",
            "helpMarkDown": "Will attempt to discover the path to the selected JDK version and set JAVA_HOME accordingly.",
            "options": {
                "default":"default",
                "1.8":"JDK 8",
                "1.7":"JDK 7",
                "1.6":"JDK 6"
            }
        },
        { 
            "name": "jdkArchitecture", 
            "type": "pickList", 
            "label": "JDK Architecture", 
            "defaultValue":"x86", 
            "required":false,
            "helpMarkDown": "Optionally supply the architecture (x86, x64) of JDK.",
            "groupName":"advanced",
            "options":{
                "x86":"x86",
                "x64":"x64"
            }
        }
    ],
    "execution": {
        "Node": {
            "target": "maven2.js",
            "argumentFormat": ""
        },
        "PowerShell": {
            "target": "$(currentDirectory)\\maven.ps1",
            "argumentFormat": "",
            "workingDirectory": "$(currentDirectory)"
        }
    }
}

=== microsoft/azure-pipelines-tasks/Tasks/CordovaBuild/task.json
{
    "id": "70E94267-15DC-434D-8973-023D766825D7",
    "name": "CordovaBuild",
    "friendlyName": "Cordova Build",
    "description": "Build a hybrid app project based on the Cordova CLI, Ionic CLI, and/or Tools for Apache Cordova ",
    "helpMarkDown": "[More Information](http://go.microsoft.com/fwlink/?LinkID=613730)",
    "category": "Build",
    "visibility": [
                "Build"
                  ],
    "author": "Microsoft Corporation",
    "version": {
        "Major": 0,
        "Minor": 0,
        "Patch": 72
    },
    "instanceNameFormat": "Cordova Build $(platform)",
     "groups": [
        {
          "name":"android",
          "displayName": "Android",
          "isExpanded": false
        },
        {
            "name":"ios",
            "displayName":"iOS",
            "isExpanded":false            
        },
        {
            "name":"windows",
            "displayName":"Windows",
            "isExpanded":false            
        },
        {
            "name":"advanced",
            "displayName":"Advanced",
            "isExpanded":false
        }
    ],
    "inputs": [
        { 
            "name": "platform", 
            "type": "string", 
            "label": "Platforms", 
            "defaultValue":"android", 
            "required":true, 
            "helpMarkDown": "Cordova platform to build. Valid options include android, ios, windows, and wp8."
        },
        { 
            "name": "configuration", 
            "type": "string", 
            "label": "Configuration", 
            "defaultValue":"$(Configuration)", 
            "required":true 
        },
        { 
            "name": "archs", 
            "type": "string", 
            "label": "Target Architectures", 
            "required":false, 
            "helpMarkDown": "Space delimited list device architectures to build. Valid options for Windows include anycpu, x86, x84, and arm. Valid options for Android include x86 and arm."
        },
        { 
            "name": "cordovaVersion", 
            "type": "string", 
            "label": "Cordova Version", 
            "required":false, 
            "helpMarkDown": "Version of Cordova tools to use to build. If not specified, looks at taco.json to determine the version and falls back on a default if no taco.json is found."
        },
        {
            "name": "antBuild",
            "type": "boolean",
            "label": "Force Ant Build",
            "required": false,
            "helpMarkDown": "Forces Cordova to use Apache Ant to build instead of Gradle on version of Cordova 5.0.0 and up.",
            "groupName":"android"   
        },
        {
            "name": "keystoreFile",
            "type": "filePath",
            "label": "Keystore File",
            "required": false,
            "helpMarkDown": "Path to the keystore file.",
            "groupName":"android"   
        },
        {
            "name": "keystorePass",
            "type": "string",
            "label": "Keystore Password",
            "required": false,
            "groupName":"android"   
        },
        {
            "name": "keystoreAlias",
            "type": "string",
            "label": "Alias",
            "required": false,
            "groupName":"android"   
        },
        {
            "name": "keyPass",
            "type": "string",
            "label": "Key Password",
            "required": false,
            "groupName":"android"   
        },
        { 
            "name": "iosSigningIdentity", 
            "type": "string", 
            "label": "Signing Identity", 
            "required":false,
            "helpMarkDown": "Optional signing identity override that should be used to sign the build. **Not required if P12 Certificate File specified.** Defaults to Xcode Project setting. You may need to select Unlock Default Keychain if you use this option.",
            "groupName":"ios"
        },
        { 
            "name": "p12", 
            "type": "filePath", 
            "label": "P12 Certificate File", 
            "required":false,
            "helpMarkDown": "Optional relative path to a PKCS12 formated p12 certificate file containing a signing certificate to be used for this build. **Omit Signing Idenity if specified.**",
            "groupName":"ios"
        },
        { 
            "name": "p12pwd", 
            "type": "string", 
            "label": "P12 Password", 
            "required":false,
            "helpMarkDown": "Password to P12 Certificate File if specified. Use a Build Variable to encrypt.",
            "groupName":"ios"
        },
        { 
            "name": "unlockDefaultKeychain", 
            "type": "boolean", 
            "label": "Unlock Default Keychain", 
            "defaultValue":false,
            "required": true,
            "helpMarkDown": "Resolve \"User interaction is not allowed\" errors by unlocking the default keychain.",
            "groupName":"ios"
        },
        { 
            "name": "defaultKeychainPassword", 
            "type": "string", 
            "label": "Default Keychain Password", 
            "required": false,
            "helpMarkDown": "Password to unlock the default keychain when this option is set.",
            "groupName":"ios"
        },
        { 
            "name": "provProfileUuid", 
            "type": "string", 
            "label": "Provisioning Profile UUID", 
            "required":false,
            "helpMarkDown": "Optional UUID of an installed provisioning profile to be used for this build. Not required if Provisioning Profile File specified. Use separate build tasks with different Schemes or Targets to specify separate provisioning profiles by target in a single workspace (iOS, WatchKit, tvOS).",
            "groupName":"ios"
        },
        { 
            "name": "provProfile", 
            "type": "filePath", 
            "label": "Provisioning Profile File", 
            "required":false,
            "helpMarkDown": "Optional relative path to file containing provisioning profile override to be used for this build. **Omit Provisioning Profile UUID if specified.** Use separate build tasks with different Schemes or Targets to specify separate provisioning profiles by target in a single workspace (iOS, WatchKit, tvOS).",
            "groupName":"ios"
        },
        { 
            "name": "removeProfile", 
            "type": "boolean", 
            "label": "Remove Profile After Build", 
            "defaultValue":false, 
            "required":false,
            "helpMarkDown": "Specifies that the contents of the Provisioning Profile File should be removed from the build agent after the build is complete. **Only check if you are running one agent per user.**",
            "groupName":"ios"
        },
        { 
            "name": "xcodeDeveloperDir", 
            "type": "string", 
            "label": "Xcode Developer Path", 
            "required":false,
            "helpMarkDown": "Optional path to Xcode Developer folder if not the system default. For use when multiple versions of Xcode are installed on a system. Ex: /Applications/Xcode 7.app/Contents/Developer",
            "groupName":"ios"
        },
        {
            "name": "windowsAppx", 
            "type": "string", 
            "label": "Windows APPX Target", 
            "required":false,
            "helpMarkDown": "Overrides type of APPX generated (Windows/Phone 8.1, 10). Valid values include: 8.1-win, 8.1-phone, uap (aka Windows/Phone 10).",
            "groupName":"windows"
        },
        { 
            "name": "args", 
            "type": "string", 
            "label": "Arguments", 
            "required":false,
            "helpMarkDown": "Additional command line arguments that should be used to build.",
            "groupName":"advanced"
        },
        { 
            "name": "cwd", 
            "type": "filePath", 
            "label": "Working Directory", 
            "defaultValue":"", 
            "required":false,
            "helpMarkDown": "Working directory for build runs. Defaults to the root of the repository.",
            "groupName":"advanced"
        },
        { 
            "name": "outputPattern", 
            "type": "string", 
            "label": "Output Directory", 
            "defaultValue":"bin", 
            "required":true,
            "helpMarkDown": "Relative path where build output (binaries) will be placed.",
            "groupName":"advanced"
        },
        { 
            "name": "targetEmulator", 
            "type": "boolean", 
            "label": "Build for Emulator/Simulator", 
            "required":false, 
            "helpMarkDown": "Build for a emulator or simulator instead of devices.",
            "groupName":"advanced"
        }
    ],
    "execution": {
        "Node": {
            "target": "cordova.js",
            "argumentFormat": ""
        },
        "PowerShell": {
            "target": "$(currentDirectory)\\bootstrapper.ps1",
            "argumentFormat": "",
            "workingDirectory": "$(currentDirectory)"
        }        
    }    
}
