=== microsoft/azure-pipelines-tasks/tasks.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "VSTS Tasks schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string",
      "description": "A unique guid for this task",
      "pattern": "^[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}$"
    },
    "name": {
      "type": "string",
      "description": "Name with no spaces",
      "pattern": "^[A-Za-z0-9\\-]+$"
    },
    "friendlyName": {
      "type": "string",
      "description": "Descriptive name (spaces allowed)"
    },
    "description": {
      "type": "string",
      "description": "Detailed description of what your task does"
    },
    "helpMarkDown": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "visibility": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Build",
          "Release",
          "Preview"
        ]
      }
    },
    "runsOn": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Agent",
          "MachineGroup",
          "Server"
        ]
      }
    },
    "category": {
      "type": "string",
      "description": "Where the task appears in VSTS",
      "enum": [
        "Build",
        "Utility",
        "Test",
        "Package",
        "Deploy"
      ]
    },
    "groups": {
      "type": "array",
      "description": "Describes groups that task properties may be logically grouped by in the UI.",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "name",
          "displayName"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "displayName": {
            "type": "string"
          },
          "isExpanded": {
            "type": "boolean"
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
                "Preview"
              ]
            }
          }
        }
      }
    },
    "demands": {
      "type": "array",
      "description": "Allows you to define a list of demands that a build agent requires to run this build task.",
      "items": {
        "type": "string"
      }
    },
    "minimumAgentVersion": {
      "type": "string",
      "pattern": "^\\d+\\.\\d+(\\.\\d+)?$"
    },
    "version": {
      "type": "object",
      "additionalProperties": false,
      "description": "Always update this when you release your task, so that the agents utilise the latest code.",
      "required": [
        "Major",
        "Minor",
        "Patch"
      ],
      "properties": {
        "Major": {
          "type": "number"
        },
        "Minor": {
          "type": [
            "number",
            "string"
          ]
        },
        "Patch": {
          "type": [
            "number",
            "string"
          ]
        }
      }
    },
    "instanceNameFormat": {
      "type": "string",
      "description": "This is how the task will be displayed within the build step list - you can use variable values by using $(variablename)"
    },
    "inputs": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "name",
          "label",
          "type"
        ],
        "properties": {
          "name": {
            "type": "string",
            "description": "The variable name to use to store the user-supplied value",
            "pattern": "^[A-Za-z][A-Za-z0-9]*$"
          },
          "label": {
            "type": "string",
            "description": "The text displayed to the user for the input label"
          },
          "type": {
            "type": "string",
            "description": "The type that dictates the control rendered to the user.",
            "enum": [
              "boolean",
              "connectedService:ServiceType",
              "connectedService:AzureRM",
              "connectedService:Azure",
              "connectedService:Azure:Certificate,UsernamePassword",
              "connectedService:Chef",
              "connectedService:ssh",
              "connectedService:Generic",
              "connectedService:Jenkins",
              "connectedService:servicefabric",
              "filePath",
              "multiLine",
              "pickList",
              "radio",
              "string"
            ]
          },
          "defaultValue": {
            "type": [
              "string",
              "boolean"
            ],
            "description": "The default value to apply to this input."
          },
          "required": {
            "type": "boolean",
            "description": "Whether the input is a required field (default is false).",
            "default": false
          },
          "helpMarkDown": {
            "type": "string",
            "description": "Help to be displayed when hovering over the help icon for the input. To display URLs use the format [Text To Display](http://Url)"
          },
          "groupName": {
            "type": "string",
            "description": "Setting this to the name of a group defined in 'groups' will place the input into that group."
          },
          "visibleRule": {
            "type": "string",
            "description": "Allow's you to define a rule which dictates when the input will be visible to a user, for example \"variableName = value\""
          },
          "properties": {
            "type": "object",
            "properties": {
              "EditableOptions": {
                "type": "string",
                "enum": [
                  "True",
                  "False"
                ]
              }
            }
          },
          "options": {
            "type": "object",
            "additionalProperties": true
          }
        }
      }
    },
    "dataSourceBindings": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "target": {
            "type": "string"
          },
          "endpointId": {
            "type": "string"
          },
          "dataSourceName": {
            "type": "string"
          },
          "parameters": {
            "type": "object"
          },
          "resultTemplate": {
            "type": "string"
          }
        }
      }
    },
    "sourceDefinitions": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "target": {
            "type": "string"
          },
          "endpoint": {
            "type": "string"
          },
          "selector": {
            "type": "string"
          },
          "keySelector": {
            "type": "string"
          },
          "authKey": {
            "type": "string"
          }
        }
      }
    },
    "execution": {
      "type": "object",
      "additionalProperties": false,
      "description": "Execution options for this task",
      "properties": {
        "Node": {
          "$ref": "#/definitions/executionObject"
        },
        "Bash": {
          "$ref": "#/definitions/executionObject"
        },
        "AzurePowerShell": {
          "$ref": "#/definitions/executionObject"
        },
        "PowerShell": {
          "$ref": "#/definitions/executionObject"
        },
        "PowerShell3": {
          "$ref": "#/definitions/executionObject"
        },
        "PowerShellExe": {
          "$ref": "#/definitions/executionObject"
        },
        "Process": {
          "$ref": "#/definitions/executionObject"
        },
        "RM:ManualIntervention": {
          "$ref": "#/definitions/executionObject"
        }
      }
    },
    "messages": {
      "type": "object"
    },
    "$schema": {
      "type": "string"
    }
  },
  "definitions": {
    "executionObject": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "target": {
          "type": "string",
          "description": "The target file to be executed. You can use variables here in brackets e.g. $(currentDirectory)\filename.ps1"
        },
        "argumentFormat": {
          "type": "string"
        },
        "workingDirectory": {
          "type": "string",
          "description": "The directory to execute the task from e.g. $(currentDirectory)"
        },
        "modifyEnvironment": {
          "type": [
            "boolean",
            "string"
          ]
        },
        "platforms": {
          "type": "array",
          "items": {
            "enum": [
              "windows"
            ]
          }
        }
      }
    }
  }
}

=== microsoft/azure-pipelines-tasks/Tasks/CopyFilesOverSSH/task.json
{
    "id": "67cec91b-0351-4c2f-8465-d74b3d2a2d96",
    "name": "CopyFilesOverSSH",
    "friendlyName": "Copy Files Over SSH",
    "description": "Copy files or build artifacts to a remote machine over SSH",
    "helpMarkDown": "[More Information](https://go.microsoft.com/fwlink/?LinkId=821894)",
    "category": "Deploy",
    "visibility": [
        "Build",
        "Release"
    ],
	"runsOn": [
        "Agent",
        "MachineGroup"
    ],
    "author": "Microsoft Corporation",
    "version": {
        "Major": 0,
        "Minor": 1,
        "Patch": 2
    },
    "demands": [],
    "instanceNameFormat": "Securely copy files to the remote machine",
    "groups": [
        {
            "name": "advanced",
            "displayName": "Advanced",
            "isExpanded": false
        }
    ],
    "inputs": [
        {
            "name": "sshEndpoint",
            "type": "connectedService:ssh",
            "label": "SSH endpoint",
            "defaultValue": "",
            "required": true,
            "helpMarkDown": "SSH endpoint with connection details for the remote machine."
        },
        {
            "name": "sourceFolder",
            "type": "filePath",
            "label": "Source folder",
            "defaultValue": "",
            "required": false,
            "helpMarkDown": "The source folder for the files to copy to the remote machine.  Empty is the root of the repo.  Use [variables](https://go.microsoft.com/fwlink/?LinkID=550988) if files are not in the repo. Example: $(agent.builddirectory)"
        },
        {
            "name": "contents",
            "type": "multiLine",
            "label": "Contents",
            "defaultValue": "**",
            "required": true,
            "helpMarkDown": "File paths to include as part of the copy. Supports multiple lines of minimatch patterns. [More Information](https://go.microsoft.com/fwlink/?LinkId=821894)"
        },
        {
            "name": "targetFolder",
            "type": "string",
            "label": "Target folder",
            "defaultValue": "",
            "required": true,
            "helpMarkDown": "Target folder on the remote machine to where files will be copied. Example: /home/user/MySite."
        },
        {
            "name": "cleanTargetFolder",
            "type": "boolean",
            "label": "Clean target folder",
            "defaultValue": "false",
            "required": false,
            "helpMarkDown": "Delete all existing files in the target folder before copying.",
            "groupName": "advanced"
        },
        {
            "name": "overwrite",
            "type": "boolean",
            "label": "Overwrite",
            "defaultValue": "true",
            "required": false,
            "helpMarkDown": "Replace existing files in the target folder.",
            "groupName": "advanced"
        },
        {
            "name": "flattenFolders",
            "type": "boolean",
            "label": "Flatten folders",
            "defaultValue": "false",
            "required": false,
            "helpMarkDown": "Flatten the folder structure and copy all files into the specified target folder on the remote machine.",
            "groupName": "advanced"
        }
    ],
    "execution": {
        "Node": {
            "target": "copyfilesoverssh.js",
            "argumentFormat": ""
        }
    },
    "messages": {
        "UseDefaultPort": "Using port 22 which is the default for SSH since no port was specified.",
        "SourceNotFolder": "Source folder has to be a valid folder path.",
        "CleanTargetFolder": "Cleaning target folder %s on the remote machine",
        "CleanTargetFolderFailed": "Failed to clean the target folder on the remote machine. %s",
        "NothingToCopy": "No files were found matching the patterns specified to copy to the remote machine.",
        "CopyingFiles": "Found %s files to copy to the remote machine.",
        "StartedFileCopy": "Copying file %s to %s on remote machine.",
        "CopyCompleted": "Completed copying %s files to the remote machine.",
        "FileExists": "File %s cannot be copied to the remote machine because it already exists and the 'Overwrite' option is disabled.",
        "SettingUpSSHConnection": "Setting up SSH connection to remote host %s.",
        "ConnectionNotSetup": "SSH connection is not set up.",
        "ConnectionFailed": "Failed to connect to remote machine. Verify the SSH endpoint details. %s.",
        "RemoteCmdExecutionErr": "Command %s failed with errors on remote machine. %s.",
        "CheckLogForStdErr": "Check the build log for STDERR from the command.",
        "RemoteCmdNonZeroExitCode": "Command %s exited with code %s.",
        "UploadFileFailed": "Failed to upload %s to %s on remote machine. %s."
    }
}

=== microsoft/azure-pipelines-tasks/Tasks/ManualIntervention/task.json
{
    "id": "BCB64569-D51A-4AF0-9C01-EA5D05B3B622",
    "name": "ManualIntervention",
    "friendlyName": "Manual Intervention",
    "description": "Pause deployment and wait for intervention",
    "helpMarkDown": "[More Information](http://go.microsoft.com/fwlink/?LinkID=825235)",
    "category": "Deploy",
    "visibility": [
        "Release"
    ],
    "author": "Microsoft Corporation",
    "runsOn": [
        "Server"
    ],
    "version": {
        "Major": 8,
        "Minor": 0,
        "Patch": 3
    },
    "inputs": [
        {
            "name": "instructions",
            "type": "multiLine",
            "label": "Instructions",
            "defaultValue": "",
            "required": false,
            "helpMarkDown": "These instructions will be shown to the user for resuming or rejecting the manual intervention. Based on these instructions the user will take an informed decision about this manual intervention.",
            "properties": {
                "resizable": "true",
                "rows": "10",
                "maxLength": "500"
            }
        },
		{
            "name": "SendEmailNotification",
            "type": "boolean",
            "label": "Send email notification",
            "defaultValue": "false",
            "required": false,
            "helpMarkDown": "Send a manual intervention pending email to all users who have Manage deployment permission. Only users with Manage deployment permission can act on a manual intervention."
			}
    ],
    "instanceNameFormat": "Manual Intervention",
    "execution": {
        "RM:ManualIntervention": {}
    }
}

=== microsoft/azure-pipelines-tasks/Tasks/Gulp/task.json
{
    "id": "B82CFBE4-34F9-40F5-889E-C8842CA9DD9D",
    "name": "Gulp",
    "friendlyName": "Gulp",
    "description": "Build with a Node.js streaming, task-based build system",
    "category": "Build",
    "visibility": [
                "Build"
                  ],    
    "author": "Microsoft Corporation",
    "version": {
        "Major": 0,
        "Minor": 1,
        "Patch": 2
    },
    "demands" : [
        "gulp"
    ],
    "groups": [
        {
            "name":"advanced",
            "displayName":"Advanced",
            "isExpanded":false
        }
    ],    
    "instanceNameFormat": "gulp $(tasks)",
    "inputs": [
        { 
            "name": "gulpFile",
            "type": "filePath",
            "label": "Gulp File Path",
            "defaultValue":"gulpfile.js",
            "required":true,
            "helpMarkDown": "Relative path from repo root of the gulp file script file to run."
        },
        {
            "name": "targets",
            "type": "string",
            "label": "Gulp Task(s)",
            "defaultValue":"",
            "helpMarkDown": "Optional.  default task will get run if not specified. Space delimited list of tasks to run.  If not specified, the default task will run.",
            "required":false
        },
        {
            "name": "arguments",
            "type": "string",
            "label": "Arguments",
            "defaultValue":"",
            "helpMarkDown": "Additional arguments passed to gulp.  --gulpfile is not needed since already added via gulpFile input above.",
            "required":false,
            "groupName":"advanced"
        },
        {
            "name": "cwd",
            "type": "filePath",
            "label": "Working Directory",
            "defaultValue":"",
            "required":false,
            "helpMarkDown": "Current working directory when script is run.  Defaults to the folder where the script is located.",
            "groupName":"advanced"
        }
    ],
    "execution": {
        "Node": {
            "target": "gulptask.js",
            "argumentFormat": ""
        }
    }
}

=== microsoft/azure-pipelines-tasks/Tasks/AndroidBuild/task.json
{
    "id": "DF857559-8715-46EB-A74E-AC98B9178AA0",
    "name": "AndroidBuild",
    "friendlyName": "Android Build",
    "description": "Build an Android app using Gradle and optionally start the emulator for unit tests",
    "category": "Build",
    "visibility": [
                "Build"
                  ],   
    "author": "Microsoft Corporation",
    "version": {
        "Major": 1,
        "Minor": 0,
        "Patch": 2
    },
    "demands" : [
	    "AndroidSDK"
    ],
    "groups":  [
        {
            "name": "emulatorOptions", 
            "displayName":"Emulator Options",
            "isExpanded":true
        }
    ],
    "inputs": [
        { 
            "name": "gradleWrapper", 
            "type": "filePath", 
            "label": "Location of Gradle Wrapper", 
            "defaultValue":"", 
            "required":false
        },
        { 
            "name": "gradleProj", 
            "type": "filePath",
            "label": "Project Directory", 
            "defaultValue":"", 
            "required":false 
        },
        { 
            "name": "gradleArguments", 
            "type": "string", 
            "label": "Arguments", 
            "defaultValue":"", 
            "required":false
        },
        { 
            "name": "startEmulator", 
            "type": "boolean", 
            "label": "Start Android Emulator", 
            "defaultValue":"False", 
            "required":false,
            "groupName":"emulatorOptions" 
        },
        { 
            "name": "emulatorTarget", 
            "type": "string", 
            "label": "Emulator Target SDK", 
            "defaultValue":"android-19", 
            "required":false, 
            "visibleRule": "startEmulator = true", 
            "groupName":"emulatorOptions" 
        },
        { 
            "name": "emulatorDevice", 
            "type": "string", 
            "label": "Emulator Device", 
            "defaultValue":"Nexus 5", 
            "required":false,
            "visibleRule": "startEmulator = true", 
            "groupName":"emulatorOptions" 
        }
    ],
    "instanceNameFormat": "Android Build $(gradleProj)",
    "execution": {
        "PowerShell": {
            "target": "$(currentDirectory)\\AndroidBuild.ps1",
            "argumentFormat": "",
            "workingDirectory": "$(currentDirectory)"
        }
    }
}

=== microsoft/azure-pipelines-tasks/Tasks/NugetPackager/task.json
{
    "id": "333b11bd-d341-40d9-afcf-b32d5ce6f24b",
    "name": "NuGetPackager",
    "friendlyName": "NuGet Packager",
    "description": "Creates nupkg outputs from csproj or nuspec files",
    "helpMarkDown": "[More Information](http://go.microsoft.com/fwlink/?LinkID=627416)",
    "category": "Package",
    "author": "Lawrence Gripper",
    "version": {
        "Major": 0,
        "Minor": 1,
        "Patch": 62
    },
    "minimumAgentVersion": "1.83.0",
    "groups": [
        {
            "name":"versioning",
            "displayName":"Versioning",
            "isExpanded":true
        },
        {
            "name":"advanced",
            "displayName":"Advanced",
            "isExpanded":false
        }
    ],    
    "instanceNameFormat": "NuGet Packager $(solution)",
    "inputs": [
        {
            "name": "searchPattern",
            "type": "filePath",
            "label": "Path/Pattern to nuspec files",
            "defaultValue":"**\\*.nuspec",
            "helpMarkDown": "Pattern to search for nuspec and csproj files to pack.",
            "required":true
        },
        {
            "name": "outputdir",
            "type": "filePath",
            "label": "Package Folder",
            "defaultValue":"",
            "helpMarkDown": "Folder where packages will be created, if empty will be created in the directory of csproj or nuspec file",
            "required":false
        },
        {
            "name": "versionByBuild",
            "type": "pickList",
            "label": "Automatic package versioning",
            "defaultValue":"false",
            "helpMarkDown": "If you choose 'Generate a prerelease string', this will generate a SemVer-compliant version formatted as `X.Y.Z-ci-datetime` where you choose X, Y, and Z.\n\nIf you choose 'From an environment variable', you must select an environment variable and ensure it contains the version number you want to use.\n\nIf you choose 'By build number', this will use the build number to version you package. **Note:** Under General set the build format to be '$(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)'.",
            "required":true,
            "groupName": "versioning",
            "options": {
                "false": "Off",
                "byPrereleaseNumber": "Generate a prerelease string",
                "byEnvVar": "From an environment variable",
                "true": "By build number"
            }
        },
        {
            "name": "versionEnvVar",
            "type": "string",
            "label": "Environment variable",
            "defaultValue":"",
            "helpMarkDown": "Enter the variable name without $, $env, or %.",
            "required":true,
            "groupName": "versioning",
            "visibleRule": "versionByBuild = byEnvVar"
        },
        {
            "name": "requestedMajorVersion",
            "type": "string",
            "label": "Major",
            "defaultValue":"1",
            "helpMarkDown": "The 'X' in version X.Y.Z",
            "required":true,
            "groupName": "versioning",
            "visibleRule": "versionByBuild = byPrereleaseNumber"
        },
        {
            "name": "requestedMinorVersion",
            "type": "string",
            "label": "Minor",
            "defaultValue":"0",
            "helpMarkDown": "The 'Y' in version X.Y.Z",
            "required":true,
            "groupName": "versioning",
            "visibleRule": "versionByBuild = byPrereleaseNumber"
        },
        {
            "name": "requestedPatchVersion",
            "type": "string",
            "label": "Patch",
            "defaultValue":"0",
            "helpMarkDown": "The 'Z' in version X.Y.Z",
            "required":true,
            "groupName": "versioning",
            "visibleRule": "versionByBuild = byPrereleaseNumber"
        },
        {
            "name": "configurationToPack",
            "type": "string",
            "label": "Configuration to Package",
            "defaultValue":"Release",
            "helpMarkDown": "When using a csproj file this specifies the configuration to package",
            "required":false,
            "groupName": "advanced"
        },
        {
            "name": "buildProperties",
            "type": "string",
            "label": "Additional build properties",
            "defaultValue": "",
            "required": false,
            "helpMarkDown": "Semicolon delimited list of properties used to build the package.",
            "groupName": "advanced"
        },
        {
            "name": "nuGetAdditionalArgs",
            "type": "string",
            "label": "NuGet Arguments",
            "defaultValue": "",
            "required": false,
            "helpMarkDown": "Additional arguments passed to NuGet.exe pack. [More Information](https://docs.nuget.org/consume/command-line-reference#user-content-pack-command).",
            "groupName": "advanced"
        },
        {
            "name": "nuGetPath",
            "type": "string",
            "label": "Path to NuGet.exe",
            "defaultValue": "",
            "required": false,
            "helpMarkDown": "Optionally supply the path to NuGet.exe",
            "groupName": "advanced"
        }

    ],
    "execution": {
        "PowerShell": {
            "target": "$(currentDirectory)\\NuGetPackager.ps1",
            "argumentFormat": "",
            "workingDirectory": ""
        }
    }
}

=== microsoft/azure-pipelines-tasks/Tasks/ArchiveFiles/task.loc.json
{
  "id": "d8b84976-e99a-4b86-b885-4849694435b0",
  "name": "ArchiveFiles",
  "friendlyName": "ms-resource:loc.friendlyName",
  "description": "ms-resource:loc.description",
  "author": "Microsoft Corporation",
  "helpMarkDown": "ms-resource:loc.helpMarkDown",
  "category": "Utility",
  "visibility": [
    "Build",
    "Release"
  ],
  "demands": [],
  "version": {
    "Major": 1,
    "Minor": 0,
    "Patch": 2
  },
  "groups": [
    {
      "name": "archive",
      "displayName": "ms-resource:loc.group.displayName.archive",
      "isExpanded": true
    }
  ],
  "instanceNameFormat": "ms-resource:loc.instanceNameFormat",
  "inputs": [
    {
      "name": "rootFolder",
      "type": "filePath",
      "label": "ms-resource:loc.input.label.rootFolder",
      "defaultValue": "$(Build.BinariesDirectory)",
      "required": true,
      "helpMarkDown": "ms-resource:loc.input.help.rootFolder"
    },
    {
      "name": "includeRootFolder",
      "type": "boolean",
      "label": "ms-resource:loc.input.label.includeRootFolder",
      "defaultValue": true,
      "required": true,
      "helpMarkDown": "ms-resource:loc.input.help.includeRootFolder"
    },
    {
      "name": "archiveType",
      "type": "pickList",
      "label": "ms-resource:loc.input.label.archiveType",
      "required": true,
      "defaultValue": "default",
      "helpMarkDown": "ms-resource:loc.input.help.archiveType",
      "groupName": "archive",
      "options": {
        "default": "zip",
        "7z": "7z",
        "tar": "tar",
        "wim": "wim"
      }
    },
    {
      "name": "tarCompression",
      "type": "pickList",
      "label": "ms-resource:loc.input.label.tarCompression",
      "required": false,
      "defaultValue": "gz",
      "helpMarkDown": "ms-resource:loc.input.help.tarCompression",
      "groupName": "archive",
      "visibleRule": "archiveType = tar",
      "options": {
        "default": "gz",
        "bz2": "bz2",
        "xz": "xz",
        "none": "None"
      }
    },
    {
      "name": "archiveFile",
      "type": "filePath",
      "label": "ms-resource:loc.input.label.archiveFile",
      "defaultValue": "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip",
      "required": true,
      "helpMarkDown": "ms-resource:loc.input.help.archiveFile",
      "groupName": "archive"
    },
    {
      "name": "replaceExistingArchive",
      "type": "boolean",
      "label": "ms-resource:loc.input.label.replaceExistingArchive",
      "required": true,
      "defaultValue": "true",
      "helpMarkDown": "ms-resource:loc.input.help.replaceExistingArchive",
      "groupName": "archive"
    }
  ],
  "execution": {
    "Node": {
      "target": "archivefiles.js",
      "argumentFormat": ""
    }
  }
}
